"""worker heartbeat

Revision ID: 0e6f4859a121
Revises: e03b42a37539
Create Date: 2026-09-25 12:58:19.124996

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e6f4859a121'
down_revision: Union[str, None] = 'e03b42a37539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('jobs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failing_ticks', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
