"""gyms, exercise notes, weight goals, streak wagers

Also workouts.gym_id and user_stats.weekly_days_4w (for similar-activity
matching).

Revision ID: 0f73caa084e4
Revises: 02c71d3228fb
Create Date: 2026-09-26 15:32:07.789699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f73caa084e4'
down_revision: Union[str, None] = '02c71d3228fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.String(length=60), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_exercise_note')
    )
    op.create_index(op.f('ix_exercise_notes_user_id'), 'exercise_notes', ['user_id'], unique=False)
    op.create_table('gyms',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plates_kg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bar_kg', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gyms_user_id'), 'gyms', ['user_id'], unique=False)
    op.create_table('streak_wagers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('days', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_streak_wager_week')
    )
    op.create_index(op.f('ix_streak_wagers_user_id'), 'streak_wagers', ['user_id'], unique=False)
    op.create_table('weight_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_kg', sa.Float(), nullable=False),
    sa.Column('start_kg', sa.Float(), nullable=False),
    sa.Column('milestone_kg', sa.Float(), nullable=False),
    sa.Column('set_on', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('user_stats', sa.Column('weekly_days_4w', sa.Float(), server_default='0', nullable=False))
    op.add_column('workouts', sa.Column('gym_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workouts_gym_id'), 'workouts', ['gym_id'], unique=False)
    op.create_foreign_key('fk_workouts_gym_id', 'workouts', 'gyms', ['gym_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workouts_gym_id', 'workouts', type_='foreignkey')
    op.drop_index(op.f('ix_workouts_gym_id'), table_name='workouts')
    op.drop_column('workouts', 'gym_id')
    op.drop_column('user_stats', 'weekly_days_4w')
    op.drop_table('weight_goals')
    op.drop_index(op.f('ix_streak_wagers_user_id'), table_name='streak_wagers')
    op.drop_table('streak_wagers')
    op.drop_index(op.f('ix_gyms_user_id'), table_name='gyms')
    op.drop_table('gyms')
    op.drop_index(op.f('ix_exercise_notes_user_id'), table_name='exercise_notes')
    op.drop_table('exercise_notes')
    # ### end Alembic commands ###
