"""kudos reactions

Revision ID: 147e798f8e56
Revises: ada4ee634382
Create Date: 2026-10-02 14:29:34.738428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147e798f8e56'
down_revision: Union[str, None] = 'ada4ee634382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kudos', sa.Column('reaction', sa.String(length=10), server_default='kudos', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kudos', 'reaction')
    # ### end Alembic commands ###
