"""terms version, email change, client errors, auth failures

Revision ID: 1ad8602d62b0
Revises: cb87a2c62f07
Create Date: 2026-09-25 14:35:51.025054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad8602d62b0'
down_revision: Union[str, None] = 'cb87a2c62f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_errors',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('stack', sa.String(length=4000), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('release', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_table('auth_failures',
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_failures_created', 'auth_failures', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_failures_email_hash'), 'auth_failures', ['email_hash'], unique=False)
    op.create_index(op.f('ix_auth_failures_ip_address'), 'auth_failures', ['ip_address'], unique=False)
    op.create_index(op.f('ix_auth_failures_user_id'), 'auth_failures', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('accepted_terms_version', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('pending_email', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###
    # Enum values can't be added inside autogenerate; ADD VALUE is safe to
    # run in a transaction on PostgreSQL 12+ as long as it isn't used in it.
    op.execute("ALTER TYPE tokenpurpose ADD VALUE IF NOT EXISTS 'email_change'")
    # Everyone who accepted before versions existed accepted the first
    # versioned wording, published the same day.
    op.execute(
        "UPDATE profiles SET accepted_terms_version = '2026-09-25' "
        "WHERE accepted_terms_at IS NOT NULL"
    )


def downgrade() -> None:
    # The 'email_change' enum value stays: PostgreSQL can't drop one, and an
    # unused value is harmless.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_email')
    op.drop_column('profiles', 'accepted_terms_version')
    op.drop_index(op.f('ix_auth_failures_user_id'), table_name='auth_failures')
    op.drop_index(op.f('ix_auth_failures_ip_address'), table_name='auth_failures')
    op.drop_index(op.f('ix_auth_failures_email_hash'), table_name='auth_failures')
    op.drop_index('ix_auth_failures_created', table_name='auth_failures')
    op.drop_table('auth_failures')
    op.drop_table('client_errors')
    # ### end Alembic commands ###
