"""trash, snooze, summary hour, backup attachment

Revision ID: 1cd8cec54e6a
Revises: 733e0613ae72
Create Date: 2026-10-02 07:39:24.775865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cd8cec54e6a'
down_revision: Union[str, None] = '733e0613ae72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trash_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trash_user_deleted', 'trash_items', ['user_id', 'deleted_at'], unique=False)
    op.add_column('habits', sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notification_preferences', sa.Column('habit_summary_hour', sa.SmallInteger(), nullable=True))
    op.add_column('notification_preferences', sa.Column('backup_attachment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'backup_attachment')
    op.drop_column('notification_preferences', 'habit_summary_hour')
    op.drop_column('habits', 'snoozed_until')
    op.drop_index('ix_trash_user_deleted', table_name='trash_items')
    op.drop_table('trash_items')
    # ### end Alembic commands ###
