"""habits: anything worth doing regularly, alongside training

Habits and their daily logs, the optional whole-life streak target on
profiles, and its projection on user_stats for the leaderboard.

Revision ID: 3917c22fc2ea
Revises: ddeaee734635
Create Date: 2026-09-26 18:45:37.036652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3917c22fc2ea'
down_revision: Union[str, None] = 'ddeaee734635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('daily_goal', sa.Float(), nullable=True),
    sa.Column('weekly_target', sa.SmallInteger(), nullable=False),
    sa.Column('time_of_day', sa.String(length=10), nullable=False),
    sa.Column('cue', sa.String(length=120), nullable=True),
    sa.Column('why', sa.String(length=200), nullable=True),
    sa.Column('total_goal', sa.Float(), nullable=True),
    sa.Column('remind_hour', sa.SmallInteger(), nullable=True),
    sa.Column('template_id', sa.String(length=40), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('check', 'duration', 'count', 'quit')", name='ck_habit_kind'),
    sa.CheckConstraint('remind_hour IS NULL OR remind_hour BETWEEN 0 AND 23', name='ck_habit_remind'),
    sa.CheckConstraint('weekly_target BETWEEN 1 AND 7', name='ck_habit_target'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('habit_logs',
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=280), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'day', name='uq_habit_log_day')
    )
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index('ix_habit_logs_user_day', 'habit_logs', ['user_id', 'day'], unique=False)
    op.add_column('profiles', sa.Column('life_target', sa.SmallInteger(), nullable=True))
    op.add_column('user_stats', sa.Column('life_streak', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'life_streak')
    op.drop_column('profiles', 'life_target')
    op.drop_index('ix_habit_logs_user_day', table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    # ### end Alembic commands ###
