"""supersets and splits

Revision ID: 3e88450d5f24
Revises: 3f4a7935ba10
Create Date: 2026-09-25 14:48:04.641587

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e88450d5f24'
down_revision: Union[str, None] = '3f4a7935ba10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('superset', sa.SmallInteger(), nullable=True))
    op.add_column('workouts', sa.Column('splits', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'splits')
    op.drop_column('workout_sets', 'superset')
    # ### end Alembic commands ###
