"""smart reminders, monthly goals, rest days

Revision ID: 3f4a7935ba10
Revises: 1ad8602d62b0
Create Date: 2026-09-25 14:43:04.008175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4a7935ba10'
down_revision: Union[str, None] = '1ad8602d62b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('days', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days BETWEEN 1 AND 31', name='ck_monthly_goal_days'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_monthly_goal')
    )
    op.create_index(op.f('ix_monthly_goals_user_id'), 'monthly_goals', ['user_id'], unique=False)
    op.create_table('rest_days',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('rest', 'sleep', 'mobility', 'sick')", name='ck_rest_kind'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_rest_day')
    )
    op.create_index(op.f('ix_rest_days_user_id'), 'rest_days', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('reminder_mode', sa.String(length=5), server_default='fixed', nullable=False))
    op.add_column('profiles', sa.Column('learned_reminder_hour', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'learned_reminder_hour')
    op.drop_column('profiles', 'reminder_mode')
    op.drop_index(op.f('ix_rest_days_user_id'), table_name='rest_days')
    op.drop_table('rest_days')
    op.drop_index(op.f('ix_monthly_goals_user_id'), table_name='monthly_goals')
    op.drop_table('monthly_goals')
    # ### end Alembic commands ###
