"""client error alerts

Revision ID: 4d85086e4198
Revises: 147e798f8e56
Create Date: 2026-10-02 14:37:27.447793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d85086e4198'
down_revision: Union[str, None] = '147e798f8e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_errors', sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_errors', 'alerted_at')
    # ### end Alembic commands ###
