"""chain requirements

Revision ID: 5997e8235479
Revises: 0e6f4859a121
Create Date: 2026-09-25 13:03:46.770036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5997e8235479'
down_revision: Union[str, None] = '0e6f4859a121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streak_chains', sa.Column('requirements_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streak_chains', 'requirements_history')
    # ### end Alembic commands ###
