"""training plans

Revision ID: 5a1672dfb2ff
Revises: d0a8e2c8eeb2
Create Date: 2026-09-25 13:20:55.623564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a1672dfb2ff'
down_revision: Union[str, None] = 'd0a8e2c8eeb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('template_id', sa.String(length=40), nullable=True),
    sa.Column('weeks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_user_id'), 'training_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_plans_user_id'), table_name='training_plans')
    op.drop_table('training_plans')
    # ### end Alembic commands ###
