"""plan challenges, coach plans, announcements

Revision ID: 679c7c30b47f
Revises: 3e88450d5f24
Create Date: 2026-09-25 14:55:49.789110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '679c7c30b47f'
down_revision: Union[str, None] = '3e88450d5f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_announcements',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_announcements_group_id'), 'group_announcements', ['group_id'], unique=False)
    op.add_column('challenges', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('training_plans', sa.Column('challenge_id', sa.UUID(), nullable=True))
    op.add_column('training_plans', sa.Column('assigned_by', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_training_plans_challenge_id'), 'training_plans', ['challenge_id'], unique=False)
    op.create_foreign_key('fk_training_plans_assigned_by', 'training_plans', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_training_plans_challenge_id', 'training_plans', 'challenges', ['challenge_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('ck_challenge_kind', 'challenges', type_='check')
    op.create_check_constraint(
        'ck_challenge_kind', 'challenges', "kind IN ('active_days', 'weekly_target', 'plan_sessions')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Plan challenges can't exist under the old constraint.
    op.execute("DELETE FROM challenges WHERE kind = 'plan_sessions'")
    op.drop_constraint('ck_challenge_kind', 'challenges', type_='check')
    op.create_check_constraint(
        'ck_challenge_kind', 'challenges', "kind IN ('active_days', 'weekly_target')"
    )
    op.drop_constraint('fk_training_plans_challenge_id', 'training_plans', type_='foreignkey')
    op.drop_constraint('fk_training_plans_assigned_by', 'training_plans', type_='foreignkey')
    op.drop_index(op.f('ix_training_plans_challenge_id'), table_name='training_plans')
    op.drop_column('training_plans', 'assigned_by')
    op.drop_column('training_plans', 'challenge_id')
    op.drop_column('challenges', 'plan')
    op.drop_index(op.f('ix_group_announcements_group_id'), table_name='group_announcements')
    op.drop_table('group_announcements')
