"""tape measurements and photo backup

Revision ID: 7ee5ccff69ad
Revises: 3917c22fc2ea
Create Date: 2026-09-27 00:04:03.355785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ee5ccff69ad"
down_revision: Union[str, None] = "3917c22fc2ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "body_photos",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("taken_on", sa.Date(), nullable=False),
        sa.Column("pose", sa.String(length=8), nullable=False),
        sa.Column("content_type", sa.String(length=32), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_body_photos_user_id"), "body_photos", ["user_id"], unique=False)
    op.add_column("body_metrics", sa.Column("neck_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("shoulders_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("chest_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("arm_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("forearm_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("hips_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("thigh_cm", sa.Float(), nullable=True))
    op.add_column("body_metrics", sa.Column("calf_cm", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("body_metrics", "calf_cm")
    op.drop_column("body_metrics", "thigh_cm")
    op.drop_column("body_metrics", "hips_cm")
    op.drop_column("body_metrics", "forearm_cm")
    op.drop_column("body_metrics", "arm_cm")
    op.drop_column("body_metrics", "chest_cm")
    op.drop_column("body_metrics", "shoulders_cm")
    op.drop_column("body_metrics", "neck_cm")
    op.drop_index(op.f("ix_body_photos_user_id"), table_name="body_photos")
    op.drop_table("body_photos")
    # ### end Alembic commands ###
