"""backup frequency and quiet days

Revision ID: ada4ee634382
Revises: d1e511ad69b6
Create Date: 2026-10-02 14:27:04.957089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada4ee634382'
down_revision: Union[str, None] = 'd1e511ad69b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('backup_frequency', sa.String(length=8), server_default='monthly', nullable=False))
    op.add_column('profiles', sa.Column('quiet_days', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'quiet_days')
    op.drop_column('notification_preferences', 'backup_frequency')
    # ### end Alembic commands ###
