"""buddies and group streaks

Revision ID: cb87a2c62f07
Revises: 5a1672dfb2ff
Create Date: 2026-09-25 13:27:58.325624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb87a2c62f07'
down_revision: Union[str, None] = '5a1672dfb2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buddy_pairs',
    sa.Column('user_a', sa.UUID(), nullable=False),
    sa.Column('user_b', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'active', 'ended')", name='ck_buddy_status'),
    sa.CheckConstraint('user_a < user_b', name='ck_buddy_order'),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a', 'user_b', name='uq_buddy_pair')
    )
    op.create_index(op.f('ix_buddy_pairs_user_a'), 'buddy_pairs', ['user_a'], unique=False)
    op.create_index(op.f('ix_buddy_pairs_user_b'), 'buddy_pairs', ['user_b'], unique=False)
    op.add_column('groups', sa.Column('streak_threshold', sa.SmallInteger(), server_default='75', nullable=False))
    op.add_column('user_stats', sa.Column('recent_weeks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'recent_weeks')
    op.drop_column('groups', 'streak_threshold')
    op.drop_index(op.f('ix_buddy_pairs_user_b'), table_name='buddy_pairs')
    op.drop_index(op.f('ix_buddy_pairs_user_a'), table_name='buddy_pairs')
    op.drop_table('buddy_pairs')
    # ### end Alembic commands ###
