"""tags and gear

Revision ID: d0a8e2c8eeb2
Revises: 623a0a3291a4
Create Date: 2026-09-25 13:11:19.784451

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0a8e2c8eeb2'
down_revision: Union[str, None] = '623a0a3291a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('default_for', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limit_m', sa.Float(), nullable=True),
    sa.Column('initial_m', sa.Float(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('shoes', 'bike', 'other')", name='ck_gear_kind'),
    sa.CheckConstraint('limit_m IS NULL OR limit_m > 0', name='ck_gear_limit'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gear_user_id'), 'gear', ['user_id'], unique=False)
    op.add_column('workouts', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('workouts', sa.Column('gear_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workouts_gear_id'), 'workouts', ['gear_id'], unique=False)
    op.create_foreign_key('fk_workouts_gear_id', 'workouts', 'gear', ['gear_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workouts_gear_id', 'workouts', type_='foreignkey')
    op.drop_index(op.f('ix_workouts_gear_id'), table_name='workouts')
    op.drop_column('workouts', 'gear_id')
    op.drop_column('workouts', 'tags')
    op.drop_index(op.f('ix_gear_user_id'), table_name='gear')
    op.drop_table('gear')
    # ### end Alembic commands ###
