"""habit schedule and pause

Revision ID: d1e511ad69b6
Revises: 1cd8cec54e6a
Create Date: 2026-10-02 14:10:38.335814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e511ad69b6'
down_revision: Union[str, None] = '1cd8cec54e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('days_mask', sa.SmallInteger(), nullable=True))
    op.add_column('habits', sa.Column('paused_from', sa.Date(), nullable=True))
    op.add_column('habits', sa.Column('paused_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'paused_until')
    op.drop_column('habits', 'paused_from')
    op.drop_column('habits', 'days_mask')
    # ### end Alembic commands ###
