"""training blocks, readiness, weekly reflections, heart rate

Also the after-session soreness/pump check-in on workouts, and an optional
max heart rate on profiles for zones.

Revision ID: ddeaee734635
Revises: 0f73caa084e4
Create Date: 2026-09-26 16:54:11.354203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddeaee734635'
down_revision: Union[str, None] = '0f73caa084e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sleep', sa.SmallInteger(), nullable=False),
    sa.Column('energy', sa.SmallInteger(), nullable=False),
    sa.Column('soreness', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sleep BETWEEN 1 AND 5 AND energy BETWEEN 1 AND 5 AND soreness BETWEEN 1 AND 5', name='ck_readiness_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_readiness_day')
    )
    op.create_index(op.f('ix_readiness_user_id'), 'readiness', ['user_id'], unique=False)
    op.create_table('training_blocks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('weeks', sa.SmallInteger(), nullable=False),
    sa.Column('rir_start', sa.SmallInteger(), nullable=False),
    sa.Column('rir_end', sa.SmallInteger(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rir_start BETWEEN 0 AND 5 AND rir_end BETWEEN 0 AND 5', name='ck_block_rir'),
    sa.CheckConstraint('weeks BETWEEN 3 AND 8', name='ck_block_weeks'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_blocks_user_id'), 'training_blocks', ['user_id'], unique=False)
    op.create_table('week_reflections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('went_well', sa.String(length=500), nullable=True),
    sa.Column('change', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_reflection_week')
    )
    op.create_index(op.f('ix_week_reflections_user_id'), 'week_reflections', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('max_hr', sa.SmallInteger(), nullable=True))
    op.add_column('workouts', sa.Column('soreness', sa.SmallInteger(), nullable=True))
    op.add_column('workouts', sa.Column('pump', sa.SmallInteger(), nullable=True))
    op.add_column('workouts', sa.Column('avg_hr', sa.SmallInteger(), nullable=True))
    op.add_column('workouts', sa.Column('max_hr', sa.SmallInteger(), nullable=True))
    op.add_column('workouts', sa.Column('hr_zones', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.create_check_constraint('ck_workouts_soreness', 'workouts', 'soreness IS NULL OR soreness BETWEEN 0 AND 3')
    op.create_check_constraint('ck_workouts_pump', 'workouts', 'pump IS NULL OR pump BETWEEN 0 AND 2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_workouts_pump', 'workouts', type_='check')
    op.drop_constraint('ck_workouts_soreness', 'workouts', type_='check')
    op.drop_column('workouts', 'hr_zones')
    op.drop_column('workouts', 'max_hr')
    op.drop_column('workouts', 'avg_hr')
    op.drop_column('workouts', 'pump')
    op.drop_column('workouts', 'soreness')
    op.drop_column('profiles', 'max_hr')
    op.drop_index(op.f('ix_week_reflections_user_id'), table_name='week_reflections')
    op.drop_table('week_reflections')
    op.drop_index(op.f('ix_training_blocks_user_id'), table_name='training_blocks')
    op.drop_table('training_blocks')
    op.drop_index(op.f('ix_readiness_user_id'), table_name='readiness')
    op.drop_table('readiness')
    # ### end Alembic commands ###
