"""product schema: profiles, training, game, social, groups, notifications

Revision ID: fd264d571db7
Revises: 9d3f1a6c1b0e
Create Date: 2026-09-24

Everything the product needs beyond auth, in one revision because none of it
has ever been deployed - there is no intermediate state worth preserving.
Autogenerated, then corrected by hand for the two things autogenerate cannot
see: the sync sequence and the new enum value.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd264d571db7"
down_revision: str | None = "9d3f1a6c1b0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate does not track sequences. workouts.seq defaults to
    # nextval('sync_seq'), so it has to exist before that table does.
    op.execute("CREATE SEQUENCE IF NOT EXISTS sync_seq")
    # Postgres 12+ allows this inside a transaction, as long as nothing in the
    # same transaction uses the new value - nothing here does.
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'moderator'")

    op.create_table(
        "activity_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("ref_key", sa.String(length=120), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "kind", "ref_key", name="uq_activity_ref"),
    )
    op.create_index(
        op.f("ix_activity_events_user_id"), "activity_events", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_events_workout_id"), "activity_events", ["workout_id"], unique=False
    )
    op.create_index("ix_activity_feed", "activity_events", ["user_id", "created_at"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_log_created", "audit_log", ["created_at"], unique=False)
    op.create_table(
        "blocks",
        sa.Column("blocker_id", sa.UUID(), nullable=False),
        sa.Column("blocked_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["blocked_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["blocker_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("blocker_id", "blocked_id", name="uq_block_pair"),
    )
    op.create_index(op.f("ix_blocks_blocked_id"), "blocks", ["blocked_id"], unique=False)
    op.create_index(op.f("ix_blocks_blocker_id"), "blocks", ["blocker_id"], unique=False)
    op.create_table(
        "body_metrics",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("measured_on", sa.Date(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("body_fat_pct", sa.Float(), nullable=True),
        sa.Column("waist_cm", sa.Float(), nullable=True),
        sa.Column("resting_hr", sa.SmallInteger(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "measured_on", name="uq_body_metric_day"),
    )
    op.create_index(op.f("ix_body_metrics_user_id"), "body_metrics", ["user_id"], unique=False)
    op.create_table(
        "custom_exercises",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("pattern", sa.String(length=20), nullable=False),
        sa.Column("equipment", sa.String(length=20), nullable=False),
        sa.Column("primary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("secondary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("load_type", sa.String(length=12), nullable=False),
        sa.Column("rest_sec", sa.Integer(), nullable=False),
        sa.Column("unilateral", sa.Boolean(), nullable=False),
        sa.Column("cue", sa.String(length=200), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_exercises_user_id"), "custom_exercises", ["user_id"], unique=False
    )
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followee_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('pending', 'accepted')", name="ck_follow_status"),
        sa.CheckConstraint("follower_id <> followee_id", name="ck_follow_not_self"),
        sa.ForeignKeyConstraint(["followee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "followee_id", name="uq_follow_pair"),
    )
    op.create_index("ix_follows_followee", "follows", ["followee_id", "status"], unique=False)
    op.create_index(op.f("ix_follows_follower_id"), "follows", ["follower_id"], unique=False)
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("invite_code", sa.String(length=16), nullable=False),
        sa.Column("avatar_hue", sa.SmallInteger(), nullable=False),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('crew', 'coaching')", name="ck_group_kind"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_invite_code"), "groups", ["invite_code"], unique=True)
    op.create_index(op.f("ix_groups_owner_id"), "groups", ["owner_id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("channels", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.String(length=400), nullable=True),
        sa.Column("url", sa.String(length=200), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dedupe_key", sa.String(length=120), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="uq_notification_dedupe"),
    )
    op.create_index(
        "ix_notifications_inbox", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "personal_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("previous", sa.Float(), nullable=True),
        sa.Column("gain_pct", sa.Float(), nullable=True),
        sa.Column("achieved_on", sa.Date(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("rewarded", sa.Boolean(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_personal_records_user_id"), "personal_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_personal_records_user_key", "personal_records", ["user_id", "key"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("handle", sa.String(length=30), nullable=True),
        sa.Column("display_name", sa.String(length=50), nullable=True),
        sa.Column("bio", sa.String(length=160), nullable=True),
        sa.Column("avatar_hue", sa.SmallInteger(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("week_starts_on", sa.SmallInteger(), nullable=False),
        sa.Column("weight_unit", sa.String(length=2), nullable=False),
        sa.Column("distance_unit", sa.String(length=2), nullable=False),
        sa.Column("training_days", sa.SmallInteger(), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("accepted_terms_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("onboarded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("visibility", sa.String(length=10), nullable=False),
        sa.Column("sharing_paused", sa.Boolean(), nullable=False),
        sa.Column("gamification_enabled", sa.Boolean(), nullable=False),
        sa.Column("leaderboard_opt_in", sa.Boolean(), nullable=False),
        sa.Column("social_suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deletion_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_hour", sa.SmallInteger(), nullable=False),
        sa.Column("quiet_start", sa.SmallInteger(), nullable=False),
        sa.Column("quiet_end", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("distance_unit IN ('km', 'mi')", name="ck_profiles_distance_unit"),
        sa.CheckConstraint(
            "visibility IN ('private', 'followers', 'public')", name="ck_profiles_visibility"
        ),
        sa.CheckConstraint("weight_unit IN ('kg', 'lb')", name="ck_profiles_weight_unit"),
        sa.CheckConstraint("reminder_hour BETWEEN 0 AND 23", name="ck_profiles_reminder_hour"),
        sa.CheckConstraint("week_starts_on BETWEEN 0 AND 6", name="ck_profiles_week_start"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_handle"), "profiles", ["handle"], unique=True)
    op.create_index(op.f("ix_profiles_user_id"), "profiles", ["user_id"], unique=True)
    op.create_table(
        "push_subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("p256dh", sa.String(length=200), nullable=False),
        sa.Column("auth", sa.String(length=100), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
    )
    op.create_index(
        op.f("ix_push_subscriptions_user_id"), "push_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("reporter_id", sa.UUID(), nullable=False),
        sa.Column("reported_user_id", sa.UUID(), nullable=True),
        sa.Column("target_type", sa.String(length=10), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=20), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("resolved_by", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('open', 'actioned', 'dismissed')", name="ck_report_status"),
        sa.CheckConstraint(
            "target_type IN ('user', 'comment', 'event', 'group', 'challenge')",
            name="ck_report_target",
        ),
        sa.ForeignKeyConstraint(["reported_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index("ix_reports_status", "reports", ["status", "created_at"], unique=False)
    op.create_table(
        "routines",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("discipline", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routines_user_id"), "routines", ["user_id"], unique=False)
    op.create_table(
        "security_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_security_events_user", "security_events", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "streak_chains",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("disciplines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_streak_chains_user_id"), "streak_chains", ["user_id"], unique=False)
    op.create_table(
        "user_achievements",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("achievement_id", sa.String(length=40), nullable=False),
        sa.Column("tier", sa.String(length=8), nullable=True),
        sa.Column("unlocked_on", sa.Date(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "achievement_id", "tier", name="uq_user_achievement_tier"),
    )
    op.create_index(
        "ix_user_achievements_achievement", "user_achievements", ["achievement_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_achievements_user_id"), "user_achievements", ["user_id"], unique=False
    )
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("computed_for", sa.Date(), nullable=False),
        sa.Column("total_xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.String(length=8), nullable=False),
        sa.Column("season_xp", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("consistency", sa.Integer(), nullable=False),
        sa.Column("this_week_days", sa.Integer(), nullable=False),
        sa.Column("this_week_target", sa.Integer(), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("active_days", sa.Integer(), nullable=False),
        sa.Column("season_prs", sa.Integer(), nullable=False),
        sa.Column("total_prs", sa.Integer(), nullable=False),
        sa.Column("last_active", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=True)
    op.create_table(
        "workouts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("discipline", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("effort", sa.SmallInteger(), nullable=True),
        sa.Column("feel", sa.SmallInteger(), nullable=True),
        sa.Column("routine_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("client_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "seq", sa.BigInteger(), server_default=sa.text("nextval('sync_seq')"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("distance_m IS NULL OR distance_m >= 0", name="ck_workouts_distance"),
        sa.CheckConstraint(
            "duration_sec IS NULL OR duration_sec >= 0", name="ck_workouts_duration"
        ),
        sa.CheckConstraint("effort IS NULL OR effort BETWEEN 1 AND 10", name="ck_workouts_effort"),
        sa.CheckConstraint("feel IS NULL OR feel BETWEEN 1 AND 5", name="ck_workouts_feel"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_workouts_user_date", "workouts", ["user_id", "local_date"], unique=False)
    op.create_index(op.f("ix_workouts_user_id"), "workouts", ["user_id"], unique=False)
    op.create_index("ix_workouts_user_seq", "workouts", ["user_id", "seq"], unique=False)
    op.create_table(
        "challenges",
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=280), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target", sa.Integer(), nullable=True),
        sa.Column("disciplines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("invite_code", sa.String(length=16), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('active_days', 'weekly_target')", name="ck_challenge_kind"),
        sa.CheckConstraint("ends_on >= starts_on", name="ck_challenge_window"),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_challenges_creator_id"), "challenges", ["creator_id"], unique=False)
    op.create_index(op.f("ix_challenges_group_id"), "challenges", ["group_id"], unique=False)
    op.create_index(op.f("ix_challenges_invite_code"), "challenges", ["invite_code"], unique=True)
    op.create_table(
        "comments",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("body", sa.String(length=280), nullable=False),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["activity_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False)
    op.create_index("ix_comments_event", "comments", ["event_id", "created_at"], unique=False)
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=8), nullable=False),
        sa.Column("shares_with_coach", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('owner', 'admin', 'coach', 'member')", name="ck_member_role"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "user_id", name="uq_group_member"),
    )
    op.create_index(op.f("ix_group_members_group_id"), "group_members", ["group_id"], unique=False)
    op.create_index(op.f("ix_group_members_user_id"), "group_members", ["user_id"], unique=False)
    op.create_table(
        "kudos",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["activity_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "user_id", name="uq_kudos_pair"),
    )
    op.create_index(op.f("ix_kudos_event_id"), "kudos", ["event_id"], unique=False)
    op.create_index(op.f("ix_kudos_user_id"), "kudos", ["user_id"], unique=False)
    op.create_table(
        "streak_repairs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("chain_id", sa.UUID(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chain_id"], ["streak_chains.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain_id", "week_start", name="uq_repair_chain_week"),
        sa.UniqueConstraint("user_id", "month", name="uq_repair_user_month"),
    )
    op.create_index(op.f("ix_streak_repairs_user_id"), "streak_repairs", ["user_id"], unique=False)
    op.create_table(
        "workout_sets",
        sa.Column("workout_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.String(length=80), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("set_index", sa.SmallInteger(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('work', 'warmup', 'drop', 'failure')", name="ck_sets_kind"),
        sa.CheckConstraint("reps IS NULL OR reps >= 0", name="ck_sets_reps"),
        sa.CheckConstraint("rpe IS NULL OR rpe BETWEEN 1 AND 10", name="ck_sets_rpe"),
        sa.CheckConstraint("weight_kg IS NULL OR weight_kg >= 0", name="ck_sets_weight"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workout_sets_user_exercise", "workout_sets", ["user_id", "exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_workout_sets_workout_id"), "workout_sets", ["workout_id"], unique=False
    )
    op.create_table(
        "challenge_participants",
        sa.Column("challenge_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.Column("final_rank", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("challenge_id", "user_id", name="uq_challenge_participant"),
    )
    op.create_index(
        op.f("ix_challenge_participants_challenge_id"),
        "challenge_participants",
        ["challenge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challenge_participants_user_id"),
        "challenge_participants",
        ["user_id"],
        unique=False,
    )


def downgrade() -> None:
    # Postgres cannot drop a value from an enum, so 'moderator' stays on
    # userrole after a downgrade. Harmless: nothing older assigns it.
    op.drop_index(op.f("ix_challenge_participants_user_id"), table_name="challenge_participants")
    op.drop_index(
        op.f("ix_challenge_participants_challenge_id"), table_name="challenge_participants"
    )
    op.drop_table("challenge_participants")
    op.drop_index(op.f("ix_workout_sets_workout_id"), table_name="workout_sets")
    op.drop_index("ix_workout_sets_user_exercise", table_name="workout_sets")
    op.drop_table("workout_sets")
    op.drop_index(op.f("ix_streak_repairs_user_id"), table_name="streak_repairs")
    op.drop_table("streak_repairs")
    op.drop_index(op.f("ix_kudos_user_id"), table_name="kudos")
    op.drop_index(op.f("ix_kudos_event_id"), table_name="kudos")
    op.drop_table("kudos")
    op.drop_index(op.f("ix_group_members_user_id"), table_name="group_members")
    op.drop_index(op.f("ix_group_members_group_id"), table_name="group_members")
    op.drop_table("group_members")
    op.drop_index("ix_comments_event", table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_challenges_invite_code"), table_name="challenges")
    op.drop_index(op.f("ix_challenges_group_id"), table_name="challenges")
    op.drop_index(op.f("ix_challenges_creator_id"), table_name="challenges")
    op.drop_table("challenges")
    op.drop_index("ix_workouts_user_seq", table_name="workouts")
    op.drop_index(op.f("ix_workouts_user_id"), table_name="workouts")
    op.drop_index("ix_workouts_user_date", table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_user_achievements_user_id"), table_name="user_achievements")
    op.drop_index("ix_user_achievements_achievement", table_name="user_achievements")
    op.drop_table("user_achievements")
    op.drop_index(op.f("ix_streak_chains_user_id"), table_name="streak_chains")
    op.drop_table("streak_chains")
    op.drop_index("ix_security_events_user", table_name="security_events")
    op.drop_table("security_events")
    op.drop_index(op.f("ix_routines_user_id"), table_name="routines")
    op.drop_table("routines")
    op.drop_index("ix_reports_status", table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_push_subscriptions_user_id"), table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.drop_index(op.f("ix_profiles_user_id"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_handle"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index("ix_personal_records_user_key", table_name="personal_records")
    op.drop_index(op.f("ix_personal_records_user_id"), table_name="personal_records")
    op.drop_table("personal_records")
    op.drop_index("ix_notifications_inbox", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_groups_owner_id"), table_name="groups")
    op.drop_index(op.f("ix_groups_invite_code"), table_name="groups")
    op.drop_table("groups")
    op.drop_index(op.f("ix_follows_follower_id"), table_name="follows")
    op.drop_index("ix_follows_followee", table_name="follows")
    op.drop_table("follows")
    op.drop_index(op.f("ix_custom_exercises_user_id"), table_name="custom_exercises")
    op.drop_table("custom_exercises")
    op.drop_index(op.f("ix_body_metrics_user_id"), table_name="body_metrics")
    op.drop_table("body_metrics")
    op.drop_index(op.f("ix_blocks_blocker_id"), table_name="blocks")
    op.drop_index(op.f("ix_blocks_blocked_id"), table_name="blocks")
    op.drop_table("blocks")
    op.drop_index("ix_audit_log_created", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_activity_feed", table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_workout_id"), table_name="activity_events")
    op.drop_index(op.f("ix_activity_events_user_id"), table_name="activity_events")
    op.drop_table("activity_events")
    op.execute("DROP SEQUENCE IF EXISTS sync_seq")
