from datetime import date, datetime
from uuid import UUID

from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class Follow(Base):
    """Asymmetric follow. Following a public account is immediate; following
    a followers-only account creates a request the other person approves."""

    __tablename__ = "follows"
    __table_args__ = (
        UniqueConstraint("follower_id", "followee_id", name="uq_follow_pair"),
        CheckConstraint("status IN ('pending', 'accepted')", name="ck_follow_status"),
        CheckConstraint("follower_id <> followee_id", name="ck_follow_not_self"),
        Index("ix_follows_followee", "followee_id", "status"),
    )

    follower_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    followee_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    status: Mapped[str] = mapped_column(String(10), default="pending", nullable=False)
    accepted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Block(Base):
    """Overrides everything: no follow either way, no feed, no kudos, no
    comments, no appearing in search or on each other's leaderboards."""

    __tablename__ = "blocks"
    __table_args__ = (UniqueConstraint("blocker_id", "blocked_id", name="uq_block_pair"),)

    blocker_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    blocked_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )


class ActivityEvent(Base):
    """Something that happened, generated by the system - never free text.

    Structured events keep moderation tractable: the only user-written text on
    the feed is comments, which are short, plain, and reportable. `data` holds
    what the client needs to render the card, snapshotted at emit time so the
    card does not change if the underlying session is later edited.
    """

    __tablename__ = "activity_events"
    __table_args__ = (
        UniqueConstraint("user_id", "kind", "ref_key", name="uq_activity_ref"),
        Index("ix_activity_feed", "user_id", "created_at"),
    )

    user_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    # workout | pr | streak | achievement | level | challenge
    kind: Mapped[str] = mapped_column(String(20), nullable=False)
    ref_key: Mapped[str] = mapped_column(String(120), nullable=False)
    data: Mapped[dict] = mapped_column(JSONB, default=dict, nullable=False)
    occurred_on: Mapped[date] = mapped_column(Date, nullable=False)
    workout_id: Mapped[UUID | None] = mapped_column(index=True)
    # Moderation soft-delete: hidden events drop out of every feed but stay
    # for the audit trail.
    hidden_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Kudos(Base):
    __tablename__ = "kudos"
    __table_args__ = (UniqueConstraint("event_id", "user_id", name="uq_kudos_pair"),)

    event_id: Mapped[UUID] = mapped_column(
        ForeignKey("activity_events.id", ondelete="CASCADE"), index=True, nullable=False
    )
    user_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )


class Comment(Base):
    """Plain text, at most 280 characters, rendered as text and never as
    markup. This is the one place users write something other users read,
    which is why api/ARCHITECTURE.md now spells out the rules for it."""

    __tablename__ = "comments"
    __table_args__ = (Index("ix_comments_event", "event_id", "created_at"),)

    event_id: Mapped[UUID] = mapped_column(
        ForeignKey("activity_events.id", ondelete="CASCADE"), nullable=False
    )
    author_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    body: Mapped[str] = mapped_column(String(280), nullable=False)
    hidden_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class Report(Base):
    __tablename__ = "reports"
    __table_args__ = (
        CheckConstraint(
            "target_type IN ('user', 'comment', 'event', 'group', 'challenge')",
            name="ck_report_target",
        ),
        CheckConstraint("status IN ('open', 'actioned', 'dismissed')", name="ck_report_status"),
        Index("ix_reports_status", "status", "created_at"),
    )

    reporter_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True, nullable=False
    )
    # SET NULL, not CASCADE: a report outlives the account it was about, for
    # the audit trail.
    reported_user_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    target_type: Mapped[str] = mapped_column(String(10), nullable=False)
    target_id: Mapped[str] = mapped_column(String(64), nullable=False)
    reason: Mapped[str] = mapped_column(String(20), nullable=False)
    detail: Mapped[str | None] = mapped_column(String(500))
    # Snapshot of the reported text, so deleting a comment does not destroy
    # the evidence a moderator needs.
    snapshot: Mapped[dict | None] = mapped_column(JSONB)
    status: Mapped[str] = mapped_column(String(10), default="open", nullable=False)
    resolved_by: Mapped[UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"))
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolution: Mapped[str | None] = mapped_column(String(200))
