"""The wider exercise catalogue, as a table.

`library.py` holds the original 84 with their reasoning; this adds the long
tail people expect to find when they search: every common variation of each
movement pattern, across barbell, dumbbell, cable, machine, kettlebell, band
and bodyweight. Sources for names, muscles and cues: the ExRx.net exercise
directory, NSCA's Essentials of Strength Training and Conditioning (4th ed.)
and the standard calisthenics progressions. Ids are permanent once shipped -
logged sets point at them - so never rename one; add an alias instead.

Columns: id, name, pattern, equipment, primary muscles, secondary muscles,
load type, rest seconds, unilateral, cue, search aliases. Muscles are
space-separated keys from MUSCLES.
"""

# fmt: off
ROWS: tuple[tuple, ...] = (
    # --- squat ------------------------------------------------------------------
    ("high-bar-squat", "High-bar back squat", "squat", "barbell", "quads glutes", "adductors lower_back", "weight", 180, False, "Bar on the traps, sit straight down between the hips, chest tall.", "olympic squat"),
    ("low-bar-squat", "Low-bar back squat", "squat", "barbell", "glutes quads", "hamstrings lower_back adductors", "weight", 180, False, "Bar below the spine of the shoulder blade, hips back a little, knees out.", "powerlifting squat"),
    ("pause-squat", "Pause squat", "squat", "barbell", "quads glutes", "adductors lower_back", "weight", 180, False, "Two-second stop at the bottom without relaxing, then drive up.", ""),
    ("box-squat", "Box squat", "squat", "barbell", "glutes quads", "hamstrings adductors", "weight", 150, False, "Sit back to the box, stay tight on it, stand without rocking.", ""),
    ("zercher-squat", "Zercher squat", "squat", "barbell", "quads glutes", "upper_back abs", "weight", 150, False, "Bar in the crooks of the elbows, elbows up, torso upright.", ""),
    ("safety-bar-squat", "Safety-bar squat", "squat", "barbell", "quads glutes", "upper_back", "weight", 180, False, "Hold the handles, push the yoke up into your back so the chest stays up.", "ssb squat"),
    ("overhead-squat", "Overhead squat", "squat", "barbell", "quads glutes", "side_delts upper_back abs", "weight", 150, False, "Wide grip, arms locked, bar over the mid-foot all the way down.", "ohs"),
    ("dumbbell-squat", "Dumbbell squat", "squat", "dumbbell", "quads glutes", "adductors", "weight", 90, False, "Dumbbells at your sides, sit between the heels, stand tall.", ""),
    ("kettlebell-goblet-squat", "Kettlebell goblet squat", "squat", "kettlebell", "quads glutes", "abs upper_back", "weight", 90, False, "Bell by the horns at the chest, elbows inside the knees at the bottom.", ""),
    ("pendulum-squat", "Pendulum squat", "squat", "machine", "quads", "glutes", "weight", 120, False, "Feet low on the platform for quads; go deep, control the arc.", ""),
    ("v-squat", "V-squat", "squat", "machine", "quads glutes", "", "weight", 120, False, "Shoulders under the pads, sit deep, drive through the whole foot.", ""),
    ("sissy-squat", "Sissy squat", "squat", "bodyweight", "quads", "", "bodyweight", 90, False, "Hold something, rise on the toes and lean back as the knees travel forward.", ""),
    ("pistol-squat", "Pistol squat", "squat", "bodyweight", "quads glutes", "abs", "bodyweight", 120, True, "Other leg straight out front, sit to the heel on one leg; hold a door to start.", "single-leg squat"),
    ("wall-sit", "Wall sit", "squat", "bodyweight", "quads", "glutes", "time", 60, False, "Back flat to the wall, thighs parallel, breathe.", ""),
    ("jump-squat", "Jump squat", "squat", "bodyweight", "quads glutes", "calves", "bodyweight", 90, False, "Quarter-to-half squat, jump, land soft and quiet.", "squat jump"),
    ("smith-split-squat", "Smith machine split squat", "lunge", "smith", "quads glutes", "", "weight", 90, True, "Long stance, front shin near vertical, drop the back knee straight down.", ""),
    ("leg-press-single", "Single-leg leg press", "squat", "machine", "quads glutes", "", "weight", 90, True, "Lighter than you think; keep the hip down on the seat.", ""),
    ("cossack-squat", "Cossack squat", "lunge", "bodyweight", "adductors quads glutes", "", "bodyweight", 75, True, "Wide stance, sit to one side with the other leg straight, toes up.", ""),
    # --- hinge -------------------------------------------------------------------
    ("sumo-deadlift", "Sumo deadlift", "hinge", "barbell", "glutes adductors quads", "hamstrings lower_back traps", "weight", 180, False, "Wide stance, hands inside the knees, push the floor apart.", "sumo"),
    ("deficit-deadlift", "Deficit deadlift", "hinge", "barbell", "hamstrings glutes lower_back", "quads traps", "weight", 180, False, "Stand on a 2-5 cm plate; same back position, longer pull.", ""),
    ("rack-pull", "Rack pull", "hinge", "barbell", "glutes lower_back traps", "hamstrings forearms", "weight", 150, False, "Bar at the knees in the rack, lock out with the hips, not the lower back.", "block pull"),
    ("stiff-leg-deadlift", "Stiff-leg deadlift", "hinge", "barbell", "hamstrings glutes", "lower_back", "weight", 150, False, "Knees soft and fixed, each rep from the floor, back flat.", "sldl"),
    ("snatch-grip-deadlift", "Snatch-grip deadlift", "hinge", "barbell", "glutes hamstrings upper_back", "traps forearms", "weight", 180, False, "Wide grip, hips lower than a normal pull, shoulders over the bar.", ""),
    ("single-leg-rdl", "Single-leg Romanian deadlift", "hinge", "dumbbell", "hamstrings glutes", "lower_back", "weight", 90, True, "Hips square, back leg and torso move as one plank.", "single leg rdl"),
    ("kettlebell-deadlift", "Kettlebell deadlift", "hinge", "kettlebell", "glutes hamstrings", "lower_back", "weight", 90, False, "Bell between the feet, hips back, stand up tall.", ""),
    ("single-arm-kettlebell-swing", "One-arm kettlebell swing", "hinge", "kettlebell", "glutes hamstrings", "obliques forearms", "weight", 90, True, "Hike it back, snap the hips, don't let the bell twist you.", ""),
    ("cable-pull-through", "Cable pull-through", "hinge", "cable", "glutes hamstrings", "", "weight", 75, False, "Rope between the legs, hips back, squeeze glutes to stand.", ""),
    ("glute-ham-raise", "Glute-ham raise", "hinge", "machine", "hamstrings glutes", "calves", "weighted_bw", 120, False, "Knees on the pad, lower slowly, curl up with the hamstrings.", "ghr"),
    ("reverse-hyperextension", "Reverse hyperextension", "hinge", "machine", "glutes lower_back", "hamstrings", "weight", 90, False, "Hips on the edge, swing the legs up with the glutes, no kick.", "reverse hyper"),
    ("single-leg-hip-thrust", "Single-leg hip thrust", "hinge", "bodyweight", "glutes", "hamstrings", "weighted_bw", 75, True, "Shoulders on a bench, one foot down, ribs down at the top.", ""),
    ("dumbbell-hip-thrust", "Dumbbell hip thrust", "hinge", "dumbbell", "glutes", "hamstrings", "weight", 90, False, "Dumbbell on the hip crease, chin tucked, pause at the top.", ""),
    ("machine-hip-thrust", "Machine hip thrust", "hinge", "machine", "glutes", "hamstrings", "weight", 90, False, "Pad on the hips, drive up to a flat torso, don't arch.", "glute drive"),
    ("barbell-glute-bridge", "Barbell glute bridge", "hinge", "barbell", "glutes", "hamstrings", "weight", 90, False, "Back on the floor, bar padded on the hips, squeeze at the top.", ""),
    ("standing-leg-curl", "Standing leg curl", "hinge", "machine", "hamstrings", "calves", "weight", 75, True, "One leg, hips still, curl the heel to the glute.", ""),
    ("stability-ball-leg-curl", "Stability-ball leg curl", "hinge", "bodyweight", "hamstrings", "glutes abs", "bodyweight", 75, False, "Hips up the whole time, roll the ball in with the heels.", "swiss ball curl"),
    ("cable-kickback", "Cable glute kickback", "hinge", "cable", "glutes", "hamstrings", "weight", 60, True, "Cuff on the ankle, hips square, kick back from the glute not the back.", "glute kickback"),
    ("frog-pump", "Frog pump", "hinge", "bodyweight", "glutes", "", "bodyweight", 60, False, "Soles together, knees out, short fast bridges.", ""),
    ("power-clean", "Power clean", "hinge", "barbell", "glutes hamstrings quads traps", "upper_back calves", "weight", 150, False, "Bar close, jump, shrug, catch on the shoulders above parallel.", "clean"),
    ("hang-clean", "Hang clean", "hinge", "barbell", "glutes hamstrings traps", "quads upper_back", "weight", 150, False, "Start above the knee, hips back, explode, fast elbows.", ""),
    ("power-snatch", "Power snatch", "hinge", "barbell", "glutes hamstrings traps", "side_delts upper_back quads", "weight", 150, False, "Wide grip, bar close, finish the jump, punch it overhead.", "snatch"),
    ("kettlebell-clean", "Kettlebell clean", "hinge", "kettlebell", "glutes hamstrings", "forearms biceps", "weight", 75, True, "Zip it up close, let the bell roll onto the wrist, don't flip it.", ""),
    ("kettlebell-snatch", "Kettlebell snatch", "hinge", "kettlebell", "glutes hamstrings side_delts", "traps", "weight", 90, True, "Swing, pull high, punch through to lockout overhead.", ""),
    # --- lunge -------------------------------------------------------------------
    ("forward-lunge", "Forward lunge", "lunge", "dumbbell", "quads glutes", "adductors", "weight", 75, True, "Step long, drop the back knee, push back to standing.", ""),
    ("barbell-lunge", "Barbell lunge", "lunge", "barbell", "quads glutes", "adductors", "weight", 90, True, "Bar on the back, step, knee to just above the floor.", ""),
    ("lateral-lunge", "Lateral lunge", "lunge", "dumbbell", "adductors glutes quads", "", "weight", 75, True, "Step wide, sit into one hip, the other leg stays straight.", "side lunge"),
    ("curtsy-lunge", "Curtsy lunge", "lunge", "dumbbell", "glutes quads", "adductors", "weight", 75, True, "Step behind and across, hips stay square.", ""),
    ("split-squat", "Split squat", "lunge", "dumbbell", "quads glutes", "", "weight", 75, True, "Feet stay put, straight down and up.", "static lunge"),
    ("front-foot-elevated-split-squat", "Front-foot elevated split squat", "lunge", "dumbbell", "quads glutes", "", "weight", 90, True, "Front foot on a plate, sink deeper than a normal split squat.", ""),
    ("barbell-step-up", "Barbell step-up", "lunge", "barbell", "quads glutes", "", "weight", 90, True, "Whole foot on the box, push through it, don't spring off the back leg.", ""),
    ("lateral-step-up", "Lateral step-up", "lunge", "dumbbell", "glutes quads", "adductors", "weight", 75, True, "Box to the side, step up through the heel.", ""),
    ("jumping-lunge", "Jumping lunge", "lunge", "bodyweight", "quads glutes", "calves", "bodyweight", 75, False, "Switch legs in the air, land soft.", "split jump"),
    ("sled-push", "Sled push", "carry", "machine", "quads glutes", "calves", "weight", 120, False, "Arms locked, low body angle, drive with short steps.", "prowler"),
    ("hip-adduction-cable", "Cable hip adduction", "lunge", "cable", "adductors", "", "weight", 60, True, "Cuff on the inside leg, sweep it across in front of the other.", ""),
    ("copenhagen-plank", "Copenhagen plank", "core", "bodyweight", "adductors obliques", "", "time", 60, True, "Top leg on a bench, lift the hips into a side plank.", "copenhagen"),
    # --- horizontal push --------------------------------------------------------
    ("decline-bench-press", "Decline bench press", "push_h", "barbell", "chest", "triceps front_delts", "weight", 150, False, "Feet hooked, bar to the lower chest.", ""),
    ("pause-bench-press", "Paused bench press", "push_h", "barbell", "chest triceps", "front_delts", "weight", 180, False, "Full stop on the chest, stay tight, press.", ""),
    ("floor-press", "Floor press", "push_h", "barbell", "triceps chest", "front_delts", "weight", 150, False, "Lying on the floor, elbows touch, press from a dead stop.", ""),
    ("spoto-press", "Spoto press", "push_h", "barbell", "chest triceps", "front_delts", "weight", 150, False, "Stop the bar an inch above the chest, hold, press.", ""),
    ("smith-bench-press", "Smith machine bench press", "push_h", "smith", "chest", "triceps front_delts", "weight", 120, False, "Set the bench so the bar lands on the lower chest.", ""),
    ("smith-incline-press", "Smith machine incline press", "push_h", "smith", "chest front_delts", "triceps", "weight", 120, False, "30-degree bench, bar to the upper chest.", ""),
    ("decline-dumbbell-press", "Decline dumbbell press", "push_h", "dumbbell", "chest", "triceps", "weight", 120, False, "Dumbbells to the lower chest, press up and slightly in.", ""),
    ("dumbbell-fly", "Dumbbell fly", "push_h", "dumbbell", "chest", "front_delts", "weight", 75, False, "Soft elbows fixed, open wide until the chest stretches, hug back.", "flye"),
    ("incline-dumbbell-fly", "Incline dumbbell fly", "push_h", "dumbbell", "chest", "front_delts", "weight", 75, False, "Low incline, wide arc, stop before the dumbbells touch.", ""),
    ("low-to-high-cable-fly", "Low-to-high cable fly", "push_h", "cable", "chest", "front_delts", "weight", 60, False, "Pulleys low, sweep up to chin height, upper chest.", ""),
    ("high-to-low-cable-fly", "High-to-low cable fly", "push_h", "cable", "chest", "", "weight", 60, False, "Pulleys high, sweep down to the hips, lower chest.", ""),
    ("incline-machine-press", "Incline machine press", "push_h", "machine", "chest front_delts", "triceps", "weight", 90, False, "Handles at the upper chest, press up and in.", ""),
    ("svend-press", "Svend press", "push_h", "dumbbell", "chest", "front_delts", "weight", 60, False, "Squeeze a plate between the palms, press straight out.", "plate press"),
    ("incline-push-up", "Incline push-up", "push_h", "bodyweight", "chest triceps", "front_delts", "bodyweight", 60, False, "Hands on a bench; the higher, the easier. Body in one line.", ""),
    ("decline-push-up", "Decline push-up", "push_h", "bodyweight", "chest front_delts", "triceps", "bodyweight", 75, False, "Feet on a bench, chest to the floor.", ""),
    ("diamond-push-up", "Diamond push-up", "push_h", "bodyweight", "triceps chest", "", "bodyweight", 75, False, "Hands together under the chest, elbows close.", "close-grip push-up"),
    ("weighted-push-up", "Weighted push-up", "push_h", "bodyweight", "chest triceps", "front_delts", "weighted_bw", 90, False, "Plate on the upper back, same strict push-up.", ""),
    ("archer-push-up", "Archer push-up", "push_h", "bodyweight", "chest triceps", "front_delts", "bodyweight", 90, True, "Wide hands, lower to one side, the other arm straight.", ""),
    ("ring-push-up", "Ring push-up", "push_h", "bodyweight", "chest triceps", "abs", "bodyweight", 75, False, "Rings close to the floor, turn the hands out at the top.", ""),
    ("bench-dip", "Bench dip", "push_h", "bodyweight", "triceps", "chest front_delts", "weighted_bw", 75, False, "Hands on a bench behind, shoulders back, down to 90 degrees.", ""),
    ("machine-dip", "Machine dip", "push_h", "machine", "triceps chest", "front_delts", "weight", 90, False, "Elbows back, chest up, full lockout.", ""),
    # --- vertical push ----------------------------------------------------------
    ("push-press", "Push press", "push_v", "barbell", "front_delts triceps", "quads side_delts upper_back", "weight", 150, False, "Short dip, drive with the legs, finish with the arms.", ""),
    ("seated-barbell-press", "Seated barbell press", "push_v", "barbell", "front_delts", "triceps side_delts", "weight", 150, False, "Upright bench, bar from the chin, head through at the top.", ""),
    ("behind-neck-press", "Behind-the-neck press", "push_v", "barbell", "front_delts side_delts", "triceps traps", "weight", 150, False, "Only with good shoulder mobility; light, to ear height.", "btn press"),
    ("smith-shoulder-press", "Smith machine shoulder press", "push_v", "smith", "front_delts", "triceps side_delts", "weight", 120, False, "Bench just behind the bar path, press to lockout.", ""),
    ("arnold-press", "Arnold press", "push_v", "dumbbell", "front_delts side_delts", "triceps", "weight", 90, False, "Palms facing you at the bottom, rotate out as you press.", ""),
    ("standing-dumbbell-press", "Standing dumbbell press", "push_v", "dumbbell", "front_delts", "triceps side_delts abs", "weight", 90, False, "Ribs down, glutes tight, press up and slightly back.", ""),
    ("single-arm-dumbbell-press", "One-arm dumbbell press", "push_v", "dumbbell", "front_delts", "triceps obliques", "weight", 90, True, "Free hand on the hip, don't lean away.", ""),
    ("kettlebell-press", "Kettlebell press", "push_v", "kettlebell", "front_delts", "triceps side_delts", "weight", 90, True, "Bell in the rack, forearm vertical, press and lock out.", ""),
    ("half-kneeling-landmine-press", "Half-kneeling landmine press", "push_v", "barbell", "front_delts chest", "triceps obliques", "weight", 90, True, "Knee down on the pressing side, push up and forward.", ""),
    ("pike-push-up", "Pike push-up", "push_v", "bodyweight", "front_delts triceps", "", "bodyweight", 90, False, "Hips high, head to the floor between the hands.", ""),
    ("handstand-push-up", "Handstand push-up", "push_v", "bodyweight", "front_delts triceps", "upper_back abs", "bodyweight", 150, False, "Against a wall, head to a pad, tripod position at the bottom.", "hspu"),
    ("z-press", "Z press", "push_v", "barbell", "front_delts triceps", "abs upper_back", "weight", 120, False, "Seated on the floor, legs straight, no back support.", ""),
    # --- horizontal pull --------------------------------------------------------
    ("pendlay-row", "Pendlay row", "pull_h", "barbell", "upper_back lats", "rear_delts biceps lower_back", "weight", 120, False, "Torso flat, each rep from the floor, explode to the chest.", ""),
    ("yates-row", "Underhand barbell row", "pull_h", "barbell", "lats upper_back", "biceps", "weight", 120, False, "Palms up, torso at 45 degrees, row to the belly.", "yates row, reverse-grip row"),
    ("seal-row", "Seal row", "pull_h", "barbell", "upper_back lats", "rear_delts biceps", "weight", 120, False, "Lying face down on a high bench, no body English possible.", ""),
    ("t-bar-row", "T-bar row", "pull_h", "barbell", "upper_back lats", "biceps rear_delts lower_back", "weight", 120, False, "Close handle, chest up, row to the stomach.", "landmine row"),
    ("meadows-row", "Meadows row", "pull_h", "barbell", "lats upper_back", "rear_delts biceps", "weight", 90, True, "Staggered stance by the landmine, row the end with an overhand grip.", ""),
    ("chest-supported-dumbbell-row", "Chest-supported dumbbell row", "pull_h", "dumbbell", "upper_back lats", "rear_delts biceps", "weight", 90, False, "Chest on an incline bench, row the elbows past the ribs.", "incline row"),
    ("kroc-row", "Heavy dumbbell row", "pull_h", "dumbbell", "lats upper_back", "forearms biceps traps", "weight", 120, True, "Heavy, for high reps, a little body English allowed.", "kroc row"),
    ("kettlebell-row", "Kettlebell row", "pull_h", "kettlebell", "lats upper_back", "biceps", "weight", 75, True, "Hinge, row the bell to the hip.", ""),
    ("single-arm-cable-row", "One-arm cable row", "pull_h", "cable", "lats upper_back", "biceps rear_delts", "weight", 75, True, "Reach long with a little rotation, row to the hip.", ""),
    ("wide-grip-cable-row", "Wide-grip cable row", "pull_h", "cable", "upper_back rear_delts", "lats", "weight", 90, False, "Overhand wide bar, row to the chest, elbows out.", ""),
    ("machine-row", "Machine row", "pull_h", "machine", "upper_back lats", "biceps rear_delts", "weight", 90, False, "Chest on the pad, drive the elbows back, slow return.", "seated row machine"),
    ("high-row-machine", "High row machine", "pull_h", "machine", "lats upper_back", "rear_delts", "weight", 90, False, "Pull down and back towards the hips.", "iso-lateral high row"),
    ("rear-delt-machine-fly", "Rear delt machine fly", "pull_h", "machine", "rear_delts", "upper_back", "weight", 60, False, "Facing the pad, arms long, sweep back to the line of the body.", "reverse pec deck"),
    ("cable-rear-delt-fly", "Cable rear delt fly", "pull_h", "cable", "rear_delts", "upper_back", "weight", 60, False, "Crossed cables at shoulder height, pull apart wide.", ""),
    ("band-pull-apart", "Band pull-apart", "pull_h", "band", "rear_delts upper_back", "", "bodyweight", 45, False, "Arms straight at chest height, pull the band to the chest.", ""),
    ("ring-row", "Ring row", "pull_h", "bodyweight", "upper_back lats", "biceps", "bodyweight", 75, False, "Body straight, pull the rings to the ribs; walk in to make it harder.", ""),
    ("prone-y-raise", "Prone Y raise", "pull_h", "dumbbell", "traps rear_delts", "upper_back", "weight", 60, False, "Chest on an incline, thumbs up, raise into a Y.", "y raise"),
    # --- vertical pull ----------------------------------------------------------
    ("wide-grip-pull-up", "Wide-grip pull-up", "pull_v", "bodyweight", "lats", "upper_back biceps", "weighted_bw", 150, False, "Hands wider than the shoulders, chest to the bar.", ""),
    ("neutral-grip-pull-up", "Neutral-grip pull-up", "pull_v", "bodyweight", "lats", "biceps upper_back", "weighted_bw", 150, False, "Parallel handles, elbows down to the ribs.", "hammer pull-up"),
    ("negative-pull-up", "Negative pull-up", "pull_v", "bodyweight", "lats", "biceps", "bodyweight", 120, False, "Jump to the top, lower for 3-5 seconds.", "eccentric pull-up"),
    ("band-assisted-pull-up", "Band-assisted pull-up", "pull_v", "band", "lats", "biceps", "bodyweight", 120, False, "Knee or foot in the band; use a lighter band as you get stronger.", ""),
    ("scapular-pull-up", "Scapular pull-up", "pull_v", "bodyweight", "lats traps", "", "bodyweight", 60, False, "Dead hang, pull the shoulder blades down without bending the arms.", "scap pull"),
    ("dead-hang", "Dead hang", "pull_v", "bodyweight", "forearms lats", "", "time", 60, False, "Hang relaxed from the bar, shoulders active not shrugged.", ""),
    ("muscle-up", "Muscle-up", "pull_v", "bodyweight", "lats triceps chest", "biceps", "bodyweight", 180, False, "Explosive pull to the hips, transition fast, press out.", ""),
    ("close-grip-pulldown", "Close-grip underhand pulldown", "pull_v", "cable", "lats biceps", "upper_back", "weight", 120, False, "Palms facing you, shoulder width, elbows to the ribs.", "reverse-grip pulldown"),
    ("wide-grip-pulldown", "Wide-grip pulldown", "pull_v", "cable", "lats upper_back", "biceps rear_delts", "weight", 120, False, "Overhand wide grip, pull to the collarbone.", ""),
    ("single-arm-pulldown", "One-arm cable pulldown", "pull_v", "cable", "lats", "biceps", "weight", 75, True, "Kneel, handle overhead, pull the elbow to the hip.", ""),
    ("machine-pulldown", "Machine pulldown", "pull_v", "machine", "lats", "biceps upper_back", "weight", 90, False, "Thighs locked under the pad, pull the handles to the chest.", ""),
    ("dumbbell-pullover", "Dumbbell pullover", "pull_v", "dumbbell", "lats chest", "triceps", "weight", 75, False, "Across a bench, arms nearly straight, stretch back, sweep over.", "pullover"),
    ("cable-pullover", "Rope cable pullover", "pull_v", "cable", "lats", "", "weight", 60, False, "Hinge a little, rope from overhead to the thighs, arms long.", ""),
    # --- shoulders ---------------------------------------------------------------
    ("front-raise", "Front raise", "shoulders", "dumbbell", "front_delts", "side_delts", "weight", 60, False, "To eye height, no swing.", ""),
    ("cable-front-raise", "Cable front raise", "shoulders", "cable", "front_delts", "", "weight", 60, False, "Facing away from a low pulley, raise to eye height.", ""),
    ("plate-front-raise", "Plate front raise", "shoulders", "dumbbell", "front_delts", "", "weight", 60, False, "Hold a plate at 3 and 9 o'clock, raise to eye height.", ""),
    ("machine-lateral-raise", "Machine lateral raise", "shoulders", "machine", "side_delts", "", "weight", 60, False, "Pads on the outside of the arms, lead with the elbows.", ""),
    ("lean-away-lateral-raise", "Lean-away lateral raise", "shoulders", "dumbbell", "side_delts", "", "weight", 60, True, "Hold a post, lean away, raise with a long arc.", ""),
    ("y-raise-cable", "Cable Y raise", "shoulders", "cable", "side_delts traps", "rear_delts", "weight", 60, False, "Crossed low cables, raise into a Y above the head.", ""),
    ("barbell-shrug", "Barbell shrug", "shoulders", "barbell", "traps", "forearms", "weight", 90, False, "Straight up to the ears, pause, no rolling.", ""),
    ("trap-bar-shrug", "Trap bar shrug", "shoulders", "barbell", "traps", "forearms", "weight", 90, False, "Handles at your sides, shrug straight up.", ""),
    ("cable-shrug", "Cable shrug", "shoulders", "cable", "traps", "", "weight", 60, False, "Low pulleys, shrug up and slightly back.", ""),
    ("external-rotation", "Cable external rotation", "shoulders", "cable", "rear_delts", "upper_back", "weight", 45, True, "Elbow pinned to the side with a towel, rotate out slowly.", "rotator cuff"),
    ("cuban-press", "Cuban press", "shoulders", "dumbbell", "rear_delts side_delts", "traps", "weight", 60, False, "Upright row to the elbows level, rotate up, press. Light.", ""),
    ("bus-driver", "Plate bus driver", "shoulders", "dumbbell", "front_delts", "side_delts", "time", 45, False, "Plate held out at arm's length, turn it like a wheel.", ""),
    # --- arms --------------------------------------------------------------------
    ("ez-bar-curl", "EZ-bar curl", "arms", "barbell", "biceps", "forearms", "weight", 75, False, "Angled grip, elbows still, curl to the chin.", "ez curl"),
    ("concentration-curl", "Concentration curl", "arms", "dumbbell", "biceps", "", "weight", 60, True, "Elbow braced on the inner thigh, squeeze at the top.", ""),
    ("spider-curl", "Spider curl", "arms", "dumbbell", "biceps", "", "weight", 60, False, "Chest on an incline bench, arms hanging, curl without swinging.", ""),
    ("bayesian-curl", "Bayesian cable curl", "arms", "cable", "biceps", "", "weight", 60, True, "Face away from a low pulley, arm behind you, curl forward.", ""),
    ("reverse-curl", "Reverse curl", "arms", "barbell", "forearms biceps", "", "weight", 60, False, "Overhand grip, curl with the wrists straight.", ""),
    ("cross-body-hammer-curl", "Cross-body hammer curl", "arms", "dumbbell", "biceps forearms", "", "weight", 60, True, "Curl across the body towards the opposite shoulder.", ""),
    ("rope-hammer-curl", "Rope hammer curl", "arms", "cable", "biceps forearms", "", "weight", 60, False, "Rope on a low pulley, thumbs up, split the rope at the top.", ""),
    ("machine-curl", "Machine curl", "arms", "machine", "biceps", "", "weight", 60, False, "Elbows lined up with the pivot, full stretch at the bottom.", ""),
    ("drag-curl", "Drag curl", "arms", "barbell", "biceps", "", "weight", 60, False, "Drag the bar up the body, elbows travel back.", ""),
    ("zottman-curl", "Zottman curl", "arms", "dumbbell", "biceps forearms", "", "weight", 60, False, "Curl palms up, turn palms down at the top, lower slowly.", ""),
    ("rope-pushdown", "Rope pushdown", "arms", "cable", "triceps", "", "weight", 60, False, "Elbows pinned, split the rope at the bottom.", ""),
    ("single-arm-pushdown", "One-arm cable pushdown", "arms", "cable", "triceps", "", "weight", 60, True, "Reverse grip or handle, lock out fully.", ""),
    ("dumbbell-overhead-extension", "Dumbbell overhead triceps extension", "arms", "dumbbell", "triceps", "", "weight", 60, False, "One dumbbell in both hands behind the head, elbows forward.", "french press"),
    ("dumbbell-skull-crusher", "Dumbbell skull crusher", "arms", "dumbbell", "triceps", "", "weight", 60, False, "Palms facing in, lower beside the head, elbows still.", ""),
    ("jm-press", "JM press", "arms", "barbell", "triceps", "chest", "weight", 90, False, "Halfway between a close-grip bench and a skull crusher; elbows forward.", ""),
    ("triceps-kickback", "Triceps kickback", "arms", "dumbbell", "triceps", "", "weight", 45, True, "Upper arm parallel to the floor, straighten fully.", ""),
    ("cable-kickback-triceps", "Cable triceps kickback", "arms", "cable", "triceps", "", "weight", 45, True, "Hinged over, upper arm fixed, extend behind.", ""),
    ("tate-press", "Tate press", "arms", "dumbbell", "triceps", "", "weight", 60, False, "Dumbbells touch the chest end to end, elbows flare, press up.", ""),
    ("machine-triceps-extension", "Machine triceps extension", "arms", "machine", "triceps", "", "weight", 60, False, "Elbows on the pad, push to full lockout.", ""),
    ("reverse-wrist-curl", "Reverse wrist curl", "arms", "dumbbell", "forearms", "", "weight", 45, False, "Forearms on the thighs, palms down, lift the knuckles.", ""),
    ("wrist-roller", "Wrist roller", "arms", "dumbbell", "forearms", "", "time", 60, False, "Arms out, roll the weight up and back down.", ""),
    ("plate-pinch", "Plate pinch", "carry", "dumbbell", "forearms", "", "time", 60, False, "Pinch two plates smooth side out, hold.", ""),
    # --- core --------------------------------------------------------------------
    ("crunch", "Crunch", "core", "bodyweight", "abs", "", "bodyweight", 45, False, "Ribs to the hips, lower back stays down.", ""),
    ("bicycle-crunch", "Bicycle crunch", "core", "bodyweight", "abs obliques", "", "bodyweight", 45, False, "Elbow towards the opposite knee, slow, legs extended.", ""),
    ("reverse-crunch", "Reverse crunch", "core", "bodyweight", "abs", "", "bodyweight", 45, False, "Curl the hips off the floor, don't swing the legs.", ""),
    ("hanging-knee-raise", "Hanging knee raise", "core", "bodyweight", "abs", "forearms", "bodyweight", 60, False, "Knees to the chest, tilt the pelvis up, no swinging.", ""),
    ("toes-to-bar", "Toes to bar", "core", "bodyweight", "abs", "lats forearms", "bodyweight", 75, False, "From a dead hang, feet to the bar, control down.", "ttb"),
    ("captains-chair-leg-raise", "Captain's chair leg raise", "core", "machine", "abs", "", "bodyweight", 60, False, "Back to the pad, raise the knees, curl the pelvis.", "vertical knee raise"),
    ("lying-leg-raise", "Lying leg raise", "core", "bodyweight", "abs", "", "bodyweight", 45, False, "Lower back flat, legs straight down slowly.", ""),
    ("v-up", "V-up", "core", "bodyweight", "abs", "", "bodyweight", 45, False, "Arms and legs meet in the middle, lower with control.", ""),
    ("hollow-hold", "Hollow body hold", "core", "bodyweight", "abs", "", "time", 45, False, "Lower back pressed down, arms and legs long and low.", "hollow hold"),
    ("russian-twist", "Russian twist", "core", "bodyweight", "obliques abs", "", "bodyweight", 45, False, "Lean back, rotate the ribs, not just the arms.", ""),
    ("woodchop", "Cable woodchop", "core", "cable", "obliques abs", "", "weight", 60, True, "High to low across the body, turn through the hips.", "wood chop"),
    ("landmine-rotation", "Landmine rotation", "core", "barbell", "obliques abs", "front_delts", "weight", 60, False, "Arms long, arc the bar hip to hip.", "landmine twist"),
    ("weighted-plank", "Weighted plank", "core", "bodyweight", "abs", "obliques", "time", 60, False, "Plate on the upper back, same straight line.", ""),
    ("rkc-plank", "Hard-style plank", "core", "bodyweight", "abs", "glutes", "time", 60, False, "Squeeze everything, pull elbows to toes; 10-20 s is plenty.", "rkc plank"),
    ("bird-dog", "Bird dog", "core", "bodyweight", "abs lower_back", "glutes", "bodyweight", 45, False, "Opposite arm and leg long, hips level, no rotation.", ""),
    ("mountain-climber", "Mountain climber", "core", "bodyweight", "abs", "quads front_delts", "time", 45, False, "Plank position, drive the knees in turn.", ""),
    ("stir-the-pot", "Stir the pot", "core", "bodyweight", "abs obliques", "", "bodyweight", 60, False, "Forearms on a ball, small circles, hips still.", ""),
    ("decline-sit-up", "Decline sit-up", "core", "bodyweight", "abs", "", "weighted_bw", 60, False, "Feet hooked, curl up, lower slowly.", ""),
    ("machine-crunch", "Machine crunch", "core", "machine", "abs", "", "weight", 60, False, "Curl the ribs to the hips, don't pull with the arms.", "ab crunch machine"),
    ("dragon-flag", "Dragon flag", "core", "bodyweight", "abs", "lats", "bodyweight", 90, False, "Hold the bench behind the head, body straight, lower slowly.", ""),
    ("l-sit", "L-sit", "core", "bodyweight", "abs", "triceps", "time", 75, False, "On parallettes or the floor, legs straight out, shoulders down.", ""),
    ("side-plank-hip-dip", "Side plank hip dip", "core", "bodyweight", "obliques", "", "bodyweight", 45, True, "Lower the hip to the floor and lift past straight.", ""),
    ("suitcase-deadlift", "Suitcase deadlift", "core", "dumbbell", "obliques glutes", "forearms", "weight", 75, True, "One weight at your side, stand without leaning.", ""),
    # --- calves -----------------------------------------------------------------
    ("leg-press-calf-raise", "Leg press calf raise", "calves", "machine", "calves", "", "weight", 60, False, "Balls of the feet on the edge, full stretch, pause at the top.", ""),
    ("single-leg-calf-raise", "Single-leg calf raise", "calves", "bodyweight", "calves", "", "weighted_bw", 45, True, "On a step, hold on, all the way down and up.", ""),
    ("smith-calf-raise", "Smith machine calf raise", "calves", "smith", "calves", "", "weight", 60, False, "On a plate, straight legs, slow stretch.", ""),
    ("donkey-calf-raise", "Donkey calf raise", "calves", "machine", "calves", "", "weight", 60, False, "Hinged forward, hips over the toes.", ""),
    ("tibialis-raise", "Tibialis raise", "calves", "bodyweight", "calves", "", "bodyweight", 45, False, "Back on a wall, heels forward, lift the toes.", "tib raise"),
    # --- carries and conditioning -------------------------------------------
    ("trap-bar-carry", "Trap bar carry", "carry", "barbell", "traps forearms", "glutes abs", "weight", 120, False, "Heavy, tall, short quick steps.", ""),
    ("overhead-carry", "Overhead carry", "carry", "kettlebell", "side_delts abs", "traps", "weight", 90, True, "Arm locked out above, ribs down, walk.", "waiter walk"),
    ("front-rack-carry", "Front-rack carry", "carry", "kettlebell", "abs upper_back", "forearms", "weight", 90, False, "Bells in the rack, elbows down, breathe behind the brace.", ""),
    ("sandbag-carry", "Sandbag carry", "carry", "dumbbell", "upper_back abs", "biceps", "weight", 120, False, "Bear-hug the bag high on the chest.", ""),
    ("sled-pull", "Sled pull", "carry", "machine", "hamstrings glutes", "upper_back", "weight", 120, False, "Walk backwards, sit low, pull with the legs.", "sled drag"),
    ("battle-ropes", "Battle ropes", "carry", "machine", "front_delts", "abs forearms", "time", 60, False, "Athletic stance, fast waves from the shoulders.", ""),
    ("burpee", "Burpee", "carry", "bodyweight", "quads chest", "abs front_delts", "bodyweight", 60, False, "Chest to the floor, jump up, clap overhead.", ""),
    ("box-jump", "Box jump", "squat", "bodyweight", "quads glutes", "calves", "bodyweight", 90, False, "Land softly in a squat, step down, don't jump down.", ""),
    ("broad-jump", "Broad jump", "squat", "bodyweight", "glutes quads", "hamstrings calves", "bodyweight", 90, False, "Swing the arms, jump out, stick the landing.", "standing long jump"),
    ("medicine-ball-slam", "Medicine ball slam", "core", "dumbbell", "abs lats", "front_delts", "weight", 60, False, "Ball overhead on the toes, slam it down with the whole body.", "ball slam"),
    ("wall-ball", "Wall ball", "squat", "dumbbell", "quads front_delts", "glutes", "weight", 75, False, "Squat, drive, throw the ball to the target.", ""),
    ("thruster", "Thruster", "squat", "barbell", "quads front_delts", "glutes triceps", "weight", 120, False, "Front squat into a press in one movement.", ""),
    ("kettlebell-thruster", "Kettlebell thruster", "squat", "kettlebell", "quads front_delts", "glutes triceps", "weight", 90, False, "Bells in the rack, squat, drive them overhead.", ""),
    ("turkish-get-up", "Turkish get-up", "core", "kettlebell", "abs front_delts", "glutes obliques", "weight", 90, True, "Eyes on the bell, arm locked, one step at a time, then reverse.", "tgu"),
    ("devil-press", "Devil press", "hinge", "dumbbell", "glutes front_delts", "chest quads", "weight", 90, False, "Burpee with the dumbbells, then swing them straight overhead.", ""),
    ("man-maker", "Man maker", "carry", "dumbbell", "chest upper_back quads", "front_delts abs", "weight", 120, False, "Push-up, row each side, clean and press.", ""),
    ("assault-bike-sprint", "Air bike sprint", "carry", "machine", "quads", "front_delts", "time", 120, False, "All-out for the interval, easy pedal between.", "assault bike"),
    ("rowing-machine-sprint", "Rowing machine sprint", "carry", "machine", "upper_back quads", "lats biceps", "time", 120, False, "Legs, then back, then arms; reverse on the return.", "erg sprint"),
    ("jump-rope", "Jump rope", "calves", "bodyweight", "calves", "", "time", 45, False, "Small hops on the balls of the feet, wrists turn the rope.", "skipping"),
    ("bear-crawl", "Bear crawl", "carry", "bodyweight", "abs front_delts", "quads", "time", 60, False, "Knees an inch off the floor, opposite hand and foot together.", ""),
)
# fmt: on
