"""The built-in catalogue: disciplines, muscles, exercises and starter routines.

Everything here is PaceStreak's own writing. The predecessor project shipped a
third-party paid program's exercise text; none of it is reproduced here, and
none should be added - this repository is AGPL, so whatever lands here is
published.

The library lives in code rather than in tables because it is versioned with
the code that interprets it: an exercise id is a stable slug that logged sets
refer to forever, and a migration to "add a row" is ceremony for no benefit.
Users add their own movements as custom exercises, which *are* rows.
"""

from dataclasses import asdict, dataclass, field

# --- disciplines -------------------------------------------------------------
#
# `metrics` tells the client which inputs to offer. `sets` means the
# exercise/set logger; the rest are single-session fields.


@dataclass(frozen=True)
class Discipline:
    id: str
    name: str
    emoji: str
    metrics: tuple[str, ...]
    verb: str


DISCIPLINES: tuple[Discipline, ...] = (
    Discipline("strength", "Strength", "🏋️", ("sets", "duration"), "Lifted"),
    Discipline("run", "Run", "🏃", ("duration", "distance", "elevation"), "Ran"),
    Discipline("ride", "Ride", "🚴", ("duration", "distance", "elevation"), "Rode"),
    Discipline("swim", "Swim", "🏊", ("duration", "distance"), "Swam"),
    Discipline("walk", "Walk & hike", "🥾", ("duration", "distance", "elevation"), "Walked"),
    Discipline("climb", "Climb", "🧗", ("duration",), "Climbed"),
    Discipline("row", "Row", "🚣", ("duration", "distance"), "Rowed"),
    Discipline("hiit", "Conditioning", "⚡", ("duration",), "Trained"),
    Discipline("yoga", "Yoga & mobility", "🧘", ("duration",), "Stretched"),
    Discipline("sport", "Sport", "⚽", ("duration",), "Played"),
    Discipline("other", "Other", "✨", ("duration", "distance"), "Trained"),
)
DISCIPLINE_IDS = frozenset(d.id for d in DISCIPLINES)
ENDURANCE = frozenset({"run", "ride", "swim", "walk", "row"})

# --- muscles and movement patterns --------------------------------------------

MUSCLES: dict[str, str] = {
    "chest": "Chest",
    "front_delts": "Front delts",
    "side_delts": "Side delts",
    "rear_delts": "Rear delts",
    "triceps": "Triceps",
    "biceps": "Biceps",
    "forearms": "Forearms",
    "lats": "Lats",
    "upper_back": "Upper back",
    "traps": "Traps",
    "lower_back": "Lower back",
    "abs": "Abs",
    "obliques": "Obliques",
    "glutes": "Glutes",
    "quads": "Quads",
    "hamstrings": "Hamstrings",
    "adductors": "Adductors",
    "calves": "Calves",
}

PATTERNS: dict[str, str] = {
    "squat": "Squat",
    "hinge": "Hinge",
    "lunge": "Lunge",
    "push_h": "Horizontal push",
    "push_v": "Vertical push",
    "pull_h": "Horizontal pull",
    "pull_v": "Vertical pull",
    "arms": "Arms",
    "shoulders": "Shoulders",
    "core": "Core",
    "calves": "Calves",
    "carry": "Carry",
}
PUSH_PATTERNS = frozenset({"push_h", "push_v"})
PULL_PATTERNS = frozenset({"pull_h", "pull_v"})

EQUIPMENT: dict[str, str] = {
    "barbell": "Barbell",
    "dumbbell": "Dumbbell",
    "cable": "Cable",
    "machine": "Machine",
    "bodyweight": "Bodyweight",
    "kettlebell": "Kettlebell",
    "band": "Band",
    "smith": "Smith machine",
}

# How load is entered. `weight` is external load; `bodyweight` logs reps only;
# `weighted_bw` is added load on a bodyweight movement; `time` logs a hold.
LOAD_TYPES = ("weight", "bodyweight", "weighted_bw", "time")


@dataclass(frozen=True)
class Exercise:
    id: str
    name: str
    pattern: str
    equipment: str
    primary: tuple[str, ...]
    secondary: tuple[str, ...] = ()
    load_type: str = "weight"
    rest_sec: int = 120
    cue: str = ""
    unilateral: bool = False
    aliases: tuple[str, ...] = field(default=())

    def to_dict(self) -> dict:
        data = asdict(self)
        data["custom"] = False
        return data


def _x(*args, **kwargs) -> Exercise:
    return Exercise(*args, **kwargs)


EXERCISES: tuple[Exercise, ...] = (
    # --- squat -----------------------------------------------------------------
    _x(
        "back-squat",
        "Back squat",
        "squat",
        "barbell",
        ("quads", "glutes"),
        ("adductors", "lower_back"),
        rest_sec=180,
        cue="Brace before you unrack, sit between your hips, and drive the floor away.",
    ),
    _x(
        "front-squat",
        "Front squat",
        "squat",
        "barbell",
        ("quads",),
        ("glutes", "upper_back"),
        rest_sec=180,
        cue="Elbows high so the bar rides on your shoulders, torso stays tall.",
    ),
    _x(
        "goblet-squat",
        "Goblet squat",
        "squat",
        "dumbbell",
        ("quads", "glutes"),
        ("abs",),
        rest_sec=90,
        cue="Hold the bell at your chest and let your elbows track inside your knees.",
    ),
    _x(
        "hack-squat",
        "Hack squat",
        "squat",
        "machine",
        ("quads",),
        ("glutes",),
        rest_sec=150,
        cue="Feet mid-platform, control the lowering, stop just short of lockout.",
    ),
    _x(
        "leg-press",
        "Leg press",
        "squat",
        "machine",
        ("quads", "glutes"),
        ("adductors",),
        rest_sec=150,
        cue="Lower until your hips want to curl off the pad, then press through mid-foot.",
    ),
    _x(
        "smith-squat",
        "Smith machine squat",
        "squat",
        "smith",
        ("quads", "glutes"),
        rest_sec=150,
        cue="Set your feet slightly forward so the fixed bar path suits your hips.",
    ),
    _x(
        "belt-squat",
        "Belt squat",
        "squat",
        "machine",
        ("quads", "glutes"),
        rest_sec=150,
        cue="Load hangs from the hips, so the spine rests - chase depth instead.",
    ),
    _x(
        "bodyweight-squat",
        "Air squat",
        "squat",
        "bodyweight",
        ("quads", "glutes"),
        load_type="bodyweight",
        rest_sec=60,
        cue="Arms forward for balance, full depth, stand up tall.",
    ),
    # --- hinge -----------------------------------------------------------------
    _x(
        "deadlift",
        "Deadlift",
        "hinge",
        "barbell",
        ("glutes", "hamstrings", "lower_back"),
        ("traps", "forearms", "quads"),
        rest_sec=210,
        cue="Bar over mid-foot, pull the slack out, then push the floor away.",
    ),
    _x(
        "romanian-deadlift",
        "Romanian deadlift",
        "hinge",
        "barbell",
        ("hamstrings", "glutes"),
        ("lower_back",),
        rest_sec=150,
        cue="Soft knees, push your hips back until the hamstrings stop you.",
    ),
    _x(
        "dumbbell-rdl",
        "Dumbbell Romanian deadlift",
        "hinge",
        "dumbbell",
        ("hamstrings", "glutes"),
        ("lower_back",),
        rest_sec=120,
        cue="Bells skim your thighs as the hips travel back, spine stays long.",
    ),
    _x(
        "trap-bar-deadlift",
        "Trap bar deadlift",
        "hinge",
        "barbell",
        ("glutes", "quads", "hamstrings"),
        ("traps",),
        rest_sec=180,
        cue="Stand in the middle, sit a little lower than a deadlift, stand up hard.",
        aliases=("hex bar deadlift",),
    ),
    _x(
        "hip-thrust",
        "Hip thrust",
        "hinge",
        "barbell",
        ("glutes",),
        ("hamstrings",),
        rest_sec=120,
        cue="Chin tucked, ribs down, finish with the glutes rather than the lower back.",
    ),
    _x(
        "glute-bridge",
        "Glute bridge",
        "hinge",
        "bodyweight",
        ("glutes",),
        ("hamstrings",),
        load_type="bodyweight",
        rest_sec=60,
        cue="Heels close, squeeze at the top for a full second.",
    ),
    _x(
        "kettlebell-swing",
        "Kettlebell swing",
        "hinge",
        "kettlebell",
        ("glutes", "hamstrings"),
        ("lower_back", "abs"),
        rest_sec=90,
        cue="Hike it back, snap the hips, let the bell float - arms are just ropes.",
    ),
    _x(
        "good-morning",
        "Good morning",
        "hinge",
        "barbell",
        ("hamstrings", "lower_back"),
        ("glutes",),
        rest_sec=150,
        cue="Light and slow. Hips back, chest down, stop before the back rounds.",
    ),
    _x(
        "back-extension",
        "Back extension",
        "hinge",
        "bodyweight",
        ("glutes", "lower_back"),
        ("hamstrings",),
        load_type="weighted_bw",
        rest_sec=90,
        cue="Hinge at the hips on the pad; hold a plate once bodyweight is easy.",
    ),
    _x(
        "lying-leg-curl",
        "Lying leg curl",
        "hinge",
        "machine",
        ("hamstrings",),
        rest_sec=90,
        cue="Hips pinned to the pad, curl all the way, lower under control.",
    ),
    _x(
        "seated-leg-curl",
        "Seated leg curl",
        "hinge",
        "machine",
        ("hamstrings",),
        rest_sec=90,
        cue="Lean forward slightly to put the hamstrings on stretch.",
    ),
    _x(
        "nordic-curl",
        "Nordic curl",
        "hinge",
        "bodyweight",
        ("hamstrings",),
        load_type="bodyweight",
        rest_sec=120,
        cue="Anchor the heels and lower as slowly as you can; push back up.",
    ),
    # --- lunge -----------------------------------------------------------------
    _x(
        "bulgarian-split-squat",
        "Bulgarian split squat",
        "lunge",
        "dumbbell",
        ("quads", "glutes"),
        ("adductors",),
        rest_sec=120,
        unilateral=True,
        cue="Rear foot on a bench, drop straight down, front knee travels forward.",
    ),
    _x(
        "walking-lunge",
        "Walking lunge",
        "lunge",
        "dumbbell",
        ("quads", "glutes"),
        ("adductors",),
        rest_sec=120,
        unilateral=True,
        cue="Long strides, back knee kisses the floor, stay tall.",
    ),
    _x(
        "reverse-lunge",
        "Reverse lunge",
        "lunge",
        "dumbbell",
        ("glutes", "quads"),
        rest_sec=90,
        unilateral=True,
        cue="Step back, not down; the front leg does the work.",
    ),
    _x(
        "step-up",
        "Step-up",
        "lunge",
        "dumbbell",
        ("quads", "glutes"),
        rest_sec=90,
        unilateral=True,
        cue="Whole foot on the box and drive through it - no push off the back leg.",
    ),
    _x(
        "leg-extension",
        "Leg extension",
        "squat",
        "machine",
        ("quads",),
        rest_sec=75,
        cue="Pause at the top, lower slower than you lifted.",
    ),
    _x(
        "hip-adduction",
        "Hip adduction",
        "lunge",
        "machine",
        ("adductors",),
        rest_sec=75,
        cue="Wide start, squeeze in, resist the pads on the way out.",
    ),
    _x(
        "hip-abduction",
        "Hip abduction",
        "lunge",
        "machine",
        ("glutes",),
        rest_sec=75,
        cue="Lean slightly forward to bias the upper glutes.",
    ),
    # --- horizontal push ---------------------------------------------------------
    _x(
        "bench-press",
        "Bench press",
        "push_h",
        "barbell",
        ("chest", "triceps"),
        ("front_delts",),
        rest_sec=180,
        cue="Shoulder blades pinned, touch the lower chest, press back towards your face.",
    ),
    _x(
        "incline-bench-press",
        "Incline bench press",
        "push_h",
        "barbell",
        ("chest", "front_delts"),
        ("triceps",),
        rest_sec=180,
        cue="Low incline, bar touches just under the collarbones.",
    ),
    _x(
        "dumbbell-bench-press",
        "Dumbbell bench press",
        "push_h",
        "dumbbell",
        ("chest", "triceps"),
        ("front_delts",),
        rest_sec=150,
        cue="Let the bells sink deep at the bottom, press up and slightly in.",
    ),
    _x(
        "incline-dumbbell-press",
        "Incline dumbbell press",
        "push_h",
        "dumbbell",
        ("chest", "front_delts"),
        ("triceps",),
        rest_sec=150,
        cue="Thirty degrees is plenty; elbows a little tucked.",
    ),
    _x(
        "machine-chest-press",
        "Machine chest press",
        "push_h",
        "machine",
        ("chest", "triceps"),
        ("front_delts",),
        rest_sec=120,
        cue="Seat so the handles meet mid-chest; chase a full stretch.",
    ),
    _x(
        "cable-fly",
        "Cable fly",
        "push_h",
        "cable",
        ("chest",),
        ("front_delts",),
        rest_sec=90,
        cue="Hug a barrel: soft elbows, arms move as one piece.",
    ),
    _x(
        "pec-deck",
        "Pec deck",
        "push_h",
        "machine",
        ("chest",),
        rest_sec=90,
        cue="Chest up, bring the pads together without shrugging.",
    ),
    _x(
        "push-up",
        "Push-up",
        "push_h",
        "bodyweight",
        ("chest", "triceps"),
        ("front_delts", "abs"),
        load_type="bodyweight",
        rest_sec=75,
        cue="A plank that moves: body in one line, chest to the floor.",
    ),
    _x(
        "dip",
        "Dip",
        "push_h",
        "bodyweight",
        ("chest", "triceps"),
        ("front_delts",),
        load_type="weighted_bw",
        rest_sec=120,
        cue="Lean forward for chest, stay upright for triceps; add weight when easy.",
    ),
    # --- vertical push -----------------------------------------------------------
    _x(
        "overhead-press",
        "Overhead press",
        "push_v",
        "barbell",
        ("front_delts", "triceps"),
        ("side_delts", "upper_back"),
        rest_sec=180,
        cue="Squeeze the glutes, press the bar past your face, finish with it over your ears.",
    ),
    _x(
        "dumbbell-shoulder-press",
        "Dumbbell shoulder press",
        "push_v",
        "dumbbell",
        ("front_delts", "triceps"),
        ("side_delts",),
        rest_sec=120,
        cue="Seated with back support, lower until the bells reach ear height.",
    ),
    _x(
        "machine-shoulder-press",
        "Machine shoulder press",
        "push_v",
        "machine",
        ("front_delts", "triceps"),
        rest_sec=120,
        cue="Handles start around chin height; press without arching.",
    ),
    _x(
        "landmine-press",
        "Landmine press",
        "push_v",
        "barbell",
        ("front_delts", "chest"),
        ("triceps",),
        rest_sec=120,
        unilateral=True,
        cue="Press up and forward along the bar's arc - kind on cranky shoulders.",
    ),
    # --- horizontal pull ---------------------------------------------------------
    _x(
        "barbell-row",
        "Barbell row",
        "pull_h",
        "barbell",
        ("upper_back", "lats"),
        ("biceps", "rear_delts", "lower_back"),
        rest_sec=150,
        cue="Hinge to about 45 degrees, pull the bar to your lower ribs.",
    ),
    _x(
        "dumbbell-row",
        "One-arm dumbbell row",
        "pull_h",
        "dumbbell",
        ("lats", "upper_back"),
        ("biceps", "rear_delts"),
        rest_sec=90,
        unilateral=True,
        cue="Pull the elbow towards your hip, let the shoulder stretch forward at the bottom.",
    ),
    _x(
        "seated-cable-row",
        "Seated cable row",
        "pull_h",
        "cable",
        ("upper_back", "lats"),
        ("biceps", "rear_delts"),
        rest_sec=120,
        cue="Chest proud, row to the stomach, reach long on the return.",
    ),
    _x(
        "v-handle-cable-row",
        "V-handle cable row",
        "pull_h",
        "cable",
        ("lats", "upper_back"),
        ("biceps", "rear_delts"),
        rest_sec=120,
        cue="Close neutral grip: row to the belly button, elbows tight, a long reach forward.",
    ),
    _x(
        "neutral-bar-cable-row",
        "Neutral-grip bar cable row",
        "pull_h",
        "cable",
        ("upper_back", "lats"),
        ("biceps", "rear_delts"),
        rest_sec=120,
        cue="Shoulder-width parallel handles: row to the lower ribs, squeeze the shoulder blades.",
    ),
    _x(
        "wide-neutral-cable-row",
        "Wide neutral-grip cable row",
        "pull_h",
        "cable",
        ("upper_back", "rear_delts"),
        ("lats", "traps"),
        rest_sec=120,
        cue="Wide parallel handles: elbows out a little, row to the chest, pinch the upper back.",
    ),
    _x(
        "chest-supported-row",
        "Chest-supported row",
        "pull_h",
        "machine",
        ("upper_back", "lats"),
        ("rear_delts", "biceps"),
        rest_sec=120,
        cue="Chest stays on the pad so the back does the rowing, not momentum.",
    ),
    _x(
        "inverted-row",
        "Inverted row",
        "pull_h",
        "bodyweight",
        ("upper_back", "lats"),
        ("biceps",),
        load_type="bodyweight",
        rest_sec=90,
        cue="Body rigid, pull your chest to the bar; walk the feet in to make it easier.",
    ),
    _x(
        "face-pull",
        "Face pull",
        "pull_h",
        "cable",
        ("rear_delts", "upper_back"),
        ("traps",),
        rest_sec=75,
        cue="Rope to your eyes, thumbs pull back and apart.",
    ),
    _x(
        "reverse-fly",
        "Reverse fly",
        "pull_h",
        "dumbbell",
        ("rear_delts",),
        ("upper_back",),
        rest_sec=75,
        cue="Hinge forward, lead with the pinkies, light weight and a slow return.",
    ),
    # --- vertical pull -----------------------------------------------------------
    _x(
        "pull-up",
        "Pull-up",
        "pull_v",
        "bodyweight",
        ("lats",),
        ("biceps", "upper_back"),
        load_type="weighted_bw",
        rest_sec=150,
        cue="Full hang to chin over bar. Add weight once sets of ten are easy.",
    ),
    _x(
        "chin-up",
        "Chin-up",
        "pull_v",
        "bodyweight",
        ("lats", "biceps"),
        ("upper_back",),
        load_type="weighted_bw",
        rest_sec=150,
        cue="Palms facing you, pull your chest to the bar.",
    ),
    _x(
        "lat-pulldown",
        "Lat pulldown",
        "pull_v",
        "cable",
        ("lats",),
        ("biceps", "upper_back"),
        rest_sec=120,
        cue="Drive the elbows down to your sides, pause with the bar at the collarbone.",
    ),
    _x(
        "v-handle-pulldown",
        "V-handle pulldown",
        "pull_v",
        "cable",
        ("lats",),
        ("biceps", "upper_back"),
        rest_sec=120,
        cue=(
            "Close neutral grip, lean back a little, pull to the upper chest with the "
            "elbows by your sides: biases the lower lats."
        ),
    ),
    _x(
        "neutral-grip-pulldown",
        "Neutral-grip pulldown",
        "pull_v",
        "cable",
        ("lats", "upper_back"),
        ("biceps",),
        rest_sec=120,
        cue=(
            "Shoulder-width parallel handles, chest up, drive the elbows down and "
            "back: works the whole back."
        ),
    ),
    _x(
        "wide-neutral-pulldown",
        "Wide neutral-grip pulldown",
        "pull_v",
        "cable",
        ("upper_back", "lats"),
        ("rear_delts", "biceps"),
        rest_sec=120,
        cue=(
            "Wide parallel handles, elbows flared a little, pull to the collarbone: "
            "biases the upper back."
        ),
    ),
    _x(
        "assisted-pull-up",
        "Assisted pull-up",
        "pull_v",
        "machine",
        ("lats",),
        ("biceps",),
        rest_sec=120,
        cue="Log the assistance as the weight; less assistance is progress.",
    ),
    _x(
        "straight-arm-pulldown",
        "Straight-arm pulldown",
        "pull_v",
        "cable",
        ("lats",),
        rest_sec=75,
        cue="Arms long, sweep the bar to your thighs from the shoulders.",
    ),
    # --- shoulders ---------------------------------------------------------------
    _x(
        "lateral-raise",
        "Lateral raise",
        "shoulders",
        "dumbbell",
        ("side_delts",),
        rest_sec=60,
        cue="Lead with the elbows, stop at shoulder height, no swinging.",
    ),
    _x(
        "cable-lateral-raise",
        "Cable lateral raise",
        "shoulders",
        "cable",
        ("side_delts",),
        rest_sec=60,
        unilateral=True,
        cue="Cable behind you so the tension starts at the bottom.",
    ),
    _x(
        "shrug",
        "Shrug",
        "shoulders",
        "dumbbell",
        ("traps",),
        rest_sec=75,
        cue="Straight up towards the ears, pause, lower slowly.",
    ),
    _x(
        "upright-row",
        "Upright row",
        "shoulders",
        "cable",
        ("side_delts", "traps"),
        rest_sec=75,
        cue="Wide grip, elbows lead, stop around chest height.",
    ),
    # --- arms --------------------------------------------------------------------
    _x(
        "barbell-curl",
        "Barbell curl",
        "arms",
        "barbell",
        ("biceps",),
        ("forearms",),
        rest_sec=75,
        cue="Elbows stay by your sides; no hip drive.",
    ),
    _x(
        "dumbbell-curl",
        "Dumbbell curl",
        "arms",
        "dumbbell",
        ("biceps",),
        ("forearms",),
        rest_sec=75,
        cue="Rotate the pinky up as you curl, lower all the way.",
    ),
    _x(
        "hammer-curl",
        "Hammer curl",
        "arms",
        "dumbbell",
        ("biceps", "forearms"),
        rest_sec=75,
        cue="Neutral grip, curl across your body or straight up.",
    ),
    _x(
        "incline-curl",
        "Incline dumbbell curl",
        "arms",
        "dumbbell",
        ("biceps",),
        rest_sec=75,
        cue="Arms hang behind you on the incline for a long stretch.",
    ),
    _x(
        "cable-curl",
        "Cable curl",
        "arms",
        "cable",
        ("biceps",),
        rest_sec=60,
        cue="Constant tension - squeeze at the top, resist on the way down.",
    ),
    _x(
        "preacher-curl",
        "Preacher curl",
        "arms",
        "machine",
        ("biceps",),
        rest_sec=75,
        cue="Armpits snug to the pad, straighten fully at the bottom.",
    ),
    _x(
        "triceps-pushdown",
        "Triceps pushdown",
        "arms",
        "cable",
        ("triceps",),
        rest_sec=60,
        cue="Elbows pinned, spread the rope at the bottom.",
    ),
    _x(
        "overhead-triceps-extension",
        "Overhead triceps extension",
        "arms",
        "cable",
        ("triceps",),
        rest_sec=75,
        cue="Face away from the stack, reach the hands behind your head for the stretch.",
    ),
    _x(
        "skull-crusher",
        "Skull crusher",
        "arms",
        "barbell",
        ("triceps",),
        rest_sec=90,
        cue="Lower the bar behind your head, not onto it; elbows stay narrow.",
    ),
    _x(
        "close-grip-bench-press",
        "Close-grip bench press",
        "push_h",
        "barbell",
        ("triceps", "chest"),
        rest_sec=150,
        cue="Hands just inside shoulder width, elbows tucked.",
    ),
    _x(
        "wrist-curl",
        "Wrist curl",
        "arms",
        "dumbbell",
        ("forearms",),
        rest_sec=60,
        cue="Forearms on your thighs, let the bar roll to the fingertips and back.",
    ),
    # --- core --------------------------------------------------------------------
    _x(
        "plank",
        "Plank",
        "core",
        "bodyweight",
        ("abs",),
        ("obliques",),
        load_type="time",
        rest_sec=60,
        cue="Squeeze glutes and pull the elbows towards the toes - hardness beats duration.",
    ),
    _x(
        "side-plank",
        "Side plank",
        "core",
        "bodyweight",
        ("obliques",),
        ("abs",),
        load_type="time",
        rest_sec=60,
        unilateral=True,
        cue="Hips high, body in one line, breathe.",
    ),
    _x(
        "hanging-leg-raise",
        "Hanging leg raise",
        "core",
        "bodyweight",
        ("abs",),
        ("forearms",),
        load_type="bodyweight",
        rest_sec=75,
        cue="Curl the pelvis up rather than swinging the legs.",
    ),
    _x(
        "cable-crunch",
        "Cable crunch",
        "core",
        "cable",
        ("abs",),
        rest_sec=60,
        cue="Hips still, curl your ribs towards your pelvis.",
    ),
    _x(
        "ab-wheel",
        "Ab wheel rollout",
        "core",
        "bodyweight",
        ("abs",),
        ("lats",),
        load_type="bodyweight",
        rest_sec=75,
        cue="Ribs down, roll only as far as your back stays flat.",
    ),
    _x(
        "dead-bug",
        "Dead bug",
        "core",
        "bodyweight",
        ("abs",),
        load_type="bodyweight",
        rest_sec=45,
        cue="Lower back glued to the floor while opposite limbs reach away.",
    ),
    _x(
        "pallof-press",
        "Pallof press",
        "core",
        "cable",
        ("obliques", "abs"),
        rest_sec=60,
        unilateral=True,
        cue="Press straight out and refuse to let the cable twist you.",
    ),
    # --- calves ------------------------------------------------------------------
    _x(
        "standing-calf-raise",
        "Standing calf raise",
        "calves",
        "machine",
        ("calves",),
        rest_sec=60,
        cue="Pause in the deep stretch, rise onto the big toe.",
    ),
    _x(
        "seated-calf-raise",
        "Seated calf raise",
        "calves",
        "machine",
        ("calves",),
        rest_sec=60,
        cue="Slow reps, full range - calves respond to the stretch.",
    ),
    # --- carry -------------------------------------------------------------------
    _x(
        "farmers-carry",
        "Farmer's carry",
        "carry",
        "dumbbell",
        ("forearms", "traps"),
        ("abs",),
        load_type="weight",
        rest_sec=90,
        cue="Tall posture, short quick steps; log distance or time as reps.",
    ),
    _x(
        "suitcase-carry",
        "Suitcase carry",
        "carry",
        "kettlebell",
        ("obliques", "forearms"),
        rest_sec=90,
        unilateral=True,
        cue="One side loaded - don't let it pull you sideways.",
    ),
)

EXERCISE_BY_ID = {e.id: e for e in EXERCISES}
CUSTOM_PREFIX = "custom-"

# --- starter routines --------------------------------------------------------
#
# Deliberately generic. They are a starting point for people who do not
# already have a plan, not a program - the app does not prescribe training.


def _item(exercise_id: str, sets: int, reps_min: int, reps_max: int, rest: int | None = None):
    return {
        "exercise_id": exercise_id,
        "sets": sets,
        "reps_min": reps_min,
        "reps_max": reps_max,
        "rest_sec": rest or EXERCISE_BY_ID[exercise_id].rest_sec,
        "target_rpe": 8,
        "note": None,
    }


TEMPLATES: tuple[dict, ...] = (
    {
        "id": "tpl-full-body-a",
        "name": "Full body A",
        "discipline": "strength",
        "summary": "Squat, press, row. Three days a week alternating with B.",
        "items": [
            _item("back-squat", 3, 5, 8),
            _item("bench-press", 3, 5, 8),
            _item("barbell-row", 3, 6, 10),
            _item("romanian-deadlift", 2, 8, 12),
            _item("plank", 2, 30, 60),
        ],
    },
    {
        "id": "tpl-full-body-b",
        "name": "Full body B",
        "discipline": "strength",
        "summary": "Hinge, overhead, pull-up. The other half of the A/B pair.",
        "items": [
            _item("deadlift", 3, 3, 6),
            _item("overhead-press", 3, 5, 8),
            _item("pull-up", 3, 5, 10),
            _item("bulgarian-split-squat", 2, 8, 12),
            _item("hanging-leg-raise", 2, 8, 15),
        ],
    },
    {
        "id": "tpl-upper",
        "name": "Upper",
        "discipline": "strength",
        "summary": "Push and pull balanced set for set.",
        "items": [
            _item("incline-dumbbell-press", 3, 6, 10),
            _item("seated-cable-row", 3, 8, 12),
            _item("dumbbell-shoulder-press", 3, 8, 12),
            _item("lat-pulldown", 3, 8, 12),
            _item("lateral-raise", 3, 12, 20),
            _item("dumbbell-curl", 2, 10, 15),
            _item("triceps-pushdown", 2, 10, 15),
        ],
    },
    {
        "id": "tpl-lower",
        "name": "Lower",
        "discipline": "strength",
        "summary": "Quads, hamstrings, glutes, calves.",
        "items": [
            _item("back-squat", 3, 5, 8),
            _item("romanian-deadlift", 3, 8, 10),
            _item("leg-press", 2, 10, 15),
            _item("lying-leg-curl", 3, 10, 15),
            _item("standing-calf-raise", 3, 10, 15),
        ],
    },
    {
        "id": "tpl-push",
        "name": "Push",
        "discipline": "strength",
        "summary": "Chest, shoulders, triceps.",
        "items": [
            _item("bench-press", 3, 5, 8),
            _item("overhead-press", 3, 6, 10),
            _item("cable-fly", 3, 10, 15),
            _item("lateral-raise", 3, 12, 20),
            _item("overhead-triceps-extension", 3, 10, 15),
        ],
    },
    {
        "id": "tpl-pull",
        "name": "Pull",
        "discipline": "strength",
        "summary": "Back, rear delts, biceps.",
        "items": [
            _item("pull-up", 3, 5, 10),
            _item("barbell-row", 3, 6, 10),
            _item("face-pull", 3, 12, 20),
            _item("hammer-curl", 3, 8, 12),
            _item("incline-curl", 2, 10, 15),
        ],
    },
    {
        "id": "tpl-legs",
        "name": "Legs",
        "discipline": "strength",
        "summary": "Squat pattern first, hinge second, accessories after.",
        "items": [
            _item("hack-squat", 3, 6, 10),
            _item("romanian-deadlift", 3, 8, 10),
            _item("walking-lunge", 2, 10, 12),
            _item("leg-extension", 2, 12, 15),
            _item("seated-leg-curl", 2, 12, 15),
            _item("seated-calf-raise", 3, 12, 20),
        ],
    },
    {
        "id": "tpl-no-equipment",
        "name": "No equipment",
        "discipline": "strength",
        "summary": "A hotel room, a living room, twenty minutes.",
        "items": [
            _item("push-up", 3, 8, 20),
            _item("bodyweight-squat", 3, 15, 25),
            _item("inverted-row", 3, 8, 15),
            _item("reverse-lunge", 2, 10, 15),
            _item("glute-bridge", 2, 15, 25),
            _item("dead-bug", 2, 8, 12),
        ],
    },
)
TEMPLATE_BY_ID = {t["id"]: t for t in TEMPLATES}


def library_payload() -> dict:
    return {
        "version": 1,
        "disciplines": [asdict(d) for d in DISCIPLINES],
        "muscles": MUSCLES,
        "patterns": PATTERNS,
        "equipment": EQUIPMENT,
        "exercises": [e.to_dict() for e in EXERCISES],
        "templates": list(TEMPLATES),
    }
